import Mathlib.Analysis.Fourier.Convolution
import Mathlib.Analysis.SpecialFunctions.Gaussian.GaussianIntegral
import RiemannGaussian.GaussianCone

/-!
# Gaussian smoothing in real Schwartz space

This file constructs Gaussian convolution without leaving Mathlib's bundled
Schwartz space.  Mathlib's Schwartz convolution is formulated for
complex-valued functions, so real Schwartz functions are complexified before
convolution and the result is then projected back to its real part.

The normalized centered Gaussian has integral one.  Its convolution with a
nonnegative even Schwartz function is again nonnegative and even.  The final
section records a precise two-part route to `SymmetricGaussianConeDense`:

* Gaussian smoothing converges to the original Schwartz function as the
  width parameter tends to infinity;
* every such smoothing lies in the closed positive cone generated by the
  symmetric translated Gaussians.

Those two approximation assertions are deliberately predicates rather than
axioms.  The theorem combining them is proved below.  This is an ordinary
Schwartz-space approximation result only: applying it to Weil's functional
would additionally require continuity in this topology, which is not supplied
and is not the classical unconditional Weil test-function topology.
-/

open Filter Set
open MeasureTheory
open scoped Convolution SchwartzMap Topology

namespace RiemannGaussian

noncomputable section

/-! ## Real convolution via complex Schwartz convolution -/

/-- Embed a real-valued Schwartz function into the complex-valued Schwartz
space. -/
def complexifySchwartz (f : RealSchwartz) : SchwartzMap ℝ ℂ :=
  f.postcompCLM Complex.ofRealCLM

@[simp]
theorem complexifySchwartz_apply (f : RealSchwartz) (x : ℝ) :
    complexifySchwartz f x = (f x : ℂ) := by
  rfl

/-- Take the real part of a complex-valued Schwartz function. -/
def realifySchwartz (f : SchwartzMap ℝ ℂ) : RealSchwartz :=
  f.postcompCLM Complex.reCLM

@[simp]
theorem realifySchwartz_apply (f : SchwartzMap ℝ ℂ) (x : ℝ) :
    realifySchwartz f x = (f x).re := by
  rfl

/-- Convolution of real-valued Schwartz functions, bundled again as a real
Schwartz function. -/
def realSchwartzConvolution (f g : RealSchwartz) : RealSchwartz :=
  realifySchwartz <|
    SchwartzMap.convolution (ContinuousLinearMap.mul ℂ ℂ)
      (complexifySchwartz f) (complexifySchwartz g)

@[simp]
theorem realSchwartzConvolution_apply (f g : RealSchwartz) (x : ℝ) :
    realSchwartzConvolution f g x = ∫ t : ℝ, f t * g (x - t) := by
  rw [realSchwartzConvolution, realifySchwartz_apply,
    SchwartzMap.convolution_apply]
  simp only [convolution_def, complexifySchwartz_apply,
    ContinuousLinearMap.mul_apply']
  simp_rw [← Complex.ofReal_mul]
  rw [integral_complex_ofReal]
  rfl

theorem realSchwartzConvolution_apply_eq_convolution
    (f g : RealSchwartz) (x : ℝ) :
    realSchwartzConvolution f g x = ((f : ℝ → ℝ) ⋆ (g : ℝ → ℝ)) x := by
  rw [realSchwartzConvolution_apply]
  rfl

/-! ## The normalized Gaussian mollifier -/

/-- The mass of `exp (-ε x²)`. -/
def gaussianMass (ε : Set.Ioi (0 : ℝ)) : ℝ :=
  Real.sqrt (Real.pi / ε.1)

theorem gaussianMass_pos (ε : Set.Ioi (0 : ℝ)) : 0 < gaussianMass ε := by
  exact Real.sqrt_pos.2 (div_pos Real.pi_pos ε.2)

theorem gaussianMass_ne_zero (ε : Set.Ioi (0 : ℝ)) : gaussianMass ε ≠ 0 :=
  ne_of_gt (gaussianMass_pos ε)

/-- The centered Gaussian normalized to have integral one. -/
def normalizedGaussianSchwartz (ε : Set.Ioi (0 : ℝ)) : RealSchwartz :=
  (gaussianMass ε)⁻¹ • centeredGaussianSchwartz ε

@[simp]
theorem normalizedGaussianSchwartz_apply (ε : Set.Ioi (0 : ℝ)) (x : ℝ) :
    normalizedGaussianSchwartz ε x =
      (gaussianMass ε)⁻¹ * Real.exp (-ε.1 * x ^ 2) := by
  simp [normalizedGaussianSchwartz]

theorem normalizedGaussianSchwartz_pos (ε : Set.Ioi (0 : ℝ)) (x : ℝ) :
    0 < normalizedGaussianSchwartz ε x := by
  rw [normalizedGaussianSchwartz_apply]
  exact mul_pos (inv_pos.2 (gaussianMass_pos ε)) (Real.exp_pos _)

theorem normalizedGaussianSchwartz_even (ε : Set.Ioi (0 : ℝ)) (x : ℝ) :
    normalizedGaussianSchwartz ε (-x) = normalizedGaussianSchwartz ε x := by
  simp [normalizedGaussianSchwartz_apply]

theorem integral_normalizedGaussianSchwartz (ε : Set.Ioi (0 : ℝ)) :
    ∫ x : ℝ, normalizedGaussianSchwartz ε x = 1 := by
  simp_rw [normalizedGaussianSchwartz_apply]
  rw [integral_const_mul, integral_gaussian]
  exact inv_mul_cancel₀ (gaussianMass_ne_zero ε)

/-! ## Gaussian smoothing -/

/-- Convolve a real Schwartz function with the normalized centered Gaussian. -/
def gaussianSmoothing (ε : Set.Ioi (0 : ℝ)) (f : RealSchwartz) : RealSchwartz :=
  realSchwartzConvolution (normalizedGaussianSchwartz ε) f

@[simp]
theorem gaussianSmoothing_apply (ε : Set.Ioi (0 : ℝ))
    (f : RealSchwartz) (x : ℝ) :
    gaussianSmoothing ε f x =
      ∫ t : ℝ, normalizedGaussianSchwartz ε t * f (x - t) := by
  exact realSchwartzConvolution_apply _ _ _

theorem gaussianSmoothing_nonnegative
    (ε : Set.Ioi (0 : ℝ)) (f : RealSchwartz)
    (hf : ∀ x, 0 ≤ f x) (x : ℝ) :
    0 ≤ gaussianSmoothing ε f x := by
  rw [gaussianSmoothing_apply]
  exact integral_nonneg fun t =>
    mul_nonneg (normalizedGaussianSchwartz_pos ε t).le (hf (x - t))

theorem gaussianSmoothing_even
    (ε : Set.Ioi (0 : ℝ)) (f : RealSchwartz)
    (hf : ∀ x, f (-x) = f x) (x : ℝ) :
    gaussianSmoothing ε f (-x) = gaussianSmoothing ε f x := by
  simp_rw [gaussianSmoothing, realSchwartzConvolution_apply_eq_convolution]
  exact convolution_neg_of_neg_eq (L := ContinuousLinearMap.mul ℝ ℝ)
    (Filter.Eventually.of_forall (normalizedGaussianSchwartz_even ε))
    (Filter.Eventually.of_forall hf)

theorem gaussianSmoothing_nonnegative_even
    (ε : Set.Ioi (0 : ℝ)) (f : RealSchwartz)
    (hf : IsNonnegativeEvenSchwartz f) :
    IsNonnegativeEvenSchwartz (gaussianSmoothing ε f) := by
  exact ⟨gaussianSmoothing_nonnegative ε f hf.1,
    gaussianSmoothing_even ε f hf.2⟩

/-! ## A concrete split of the density theorem -/

/-- Gaussian mollification converges in the Schwartz topology as the inverse
variance tends to infinity. -/
def GaussianSmoothingConverges : Prop :=
  ∀ f : RealSchwartz,
    Tendsto (fun ε : Set.Ioi (0 : ℝ) => gaussianSmoothing ε f) atTop (nhds f)

/-- Every smoothing of a nonnegative even Schwartz function is in the closed
positive cone generated by symmetric translated Gaussians. -/
def GaussianSmoothingInConeClosure
    (G : PositiveGaussianIndex → RealSchwartz) : Prop :=
  ∀ (ε : Set.Ioi (0 : ℝ)) (f : RealSchwartz),
    IsNonnegativeEvenSchwartz f →
      gaussianSmoothing ε f ∈ closure (generatorCone G : Set RealSchwartz)

/-- The two concrete Gaussian-approximation assertions imply the density
statement used by `full_even_schwartz_positivity_of_gaussian`. -/
theorem symmetricGaussianConeDense_of_smoothing
    (G : PositiveGaussianIndex → RealSchwartz)
    (hConverges : GaussianSmoothingConverges)
    (hCone : GaussianSmoothingInConeClosure G) :
    SymmetricGaussianConeDense G := by
  intro f hf
  apply isClosed_closure.mem_of_tendsto (hConverges f)
  exact Filter.Eventually.of_forall fun ε => hCone ε f hf

end

end RiemannGaussian
