import Mathlib.Analysis.Distribution.SchwartzSpace.Basic
import Mathlib.Geometry.Convex.Cone.Basic
import RiemannGaussian.GaussianSchwartz

/-!
# The closed positive cone generated by symmetric Gaussians

This file isolates an abstract functional-analytic implication considered by
the Gaussian-Weil strategy.  A continuous real-linear functional which is
nonnegative on a family of generators is nonnegative on the closure of their
positive cone.  Consequently, density of the symmetric Gaussian generators
inside the nonnegative even Schwartz functions is exactly the remaining
approximation statement for this abstract Schwartz-space route.

No Weil explicit formula or Riemann-hypothesis equivalence is assumed here.
In particular, this theorem does not assert that the unconditional Weil
functional is continuous on ordinary Schwartz space.  Its classical domain
must retain analytic continuation across the critical strip; see
`GaussianSpectral.lean` and the bridge audit in the research pack.
-/

open Set
open scoped SchwartzMap

namespace RiemannGaussian

noncomputable section

section AbstractCone

variable {ι V : Type*}
variable [TopologicalSpace V] [AddCommMonoid V] [Module ℝ V]

/-- The (strictly) positive finite cone generated by `g`.  Its topological
closure also contains zero and limits of positive finite combinations. -/
def generatorCone (g : ι → V) : ConvexCone ℝ V :=
  ConvexCone.hull ℝ (range g)

/-- The cone on which a real linear functional is nonnegative. -/
def functionalNonnegativeCone (W : V →L[ℝ] ℝ) : ConvexCone ℝ V where
  carrier := {x | 0 ≤ W x}
  smul_mem' := by
    intro c hc x hx
    change 0 ≤ W (c • x)
    rw [map_smul]
    exact mul_nonneg hc.le hx
  add_mem' := by
    intro x hx y hy
    change 0 ≤ W (x + y)
    rw [map_add]
    exact add_nonneg hx hy

lemma isClosed_functionalNonnegativeCone (W : V →L[ℝ] ℝ) :
    IsClosed (functionalNonnegativeCone W : Set V) := by
  exact isClosed_Ici.preimage W.continuous

/-- Positivity on generators extends, by linearity and continuity, to their
closed positive cone. -/
theorem nonnegative_on_closure_generatorCone
    (W : V →L[ℝ] ℝ) (g : ι → V)
    (hg : ∀ i, 0 ≤ W (g i)) :
    ∀ x ∈ closure (generatorCone g : Set V), 0 ≤ W x := by
  have hcone : (generatorCone g : Set V) ⊆ functionalNonnegativeCone W := by
    apply ConvexCone.hull_min
    rintro x ⟨i, rfl⟩
    exact hg i
  have hclosure :
      closure (generatorCone g : Set V) ⊆ functionalNonnegativeCone W :=
    closure_minimal hcone (isClosed_functionalNonnegativeCone W)
  intro x hx
  exact hclosure hx

end AbstractCone

/-! ## Specialization to the Gaussian-Weil test family -/

/-- Pointwise nonnegative, even real Schwartz functions. -/
def IsNonnegativeEvenSchwartz (f : RealSchwartz) : Prop :=
  (∀ x, 0 ≤ f x) ∧ (∀ x, f (-x) = f x)

/-- `G` realizes the concrete symmetric Gaussians defined in
`GaussianHeat.lean`. -/
def RealizesSymmetricGaussians (G : PositiveGaussianIndex → RealSchwartz) : Prop :=
  ∀ p r, G p r = symmetricGaussian p.1.1 p.2 r

theorem symmetricGaussianSchwartz_realizes :
    RealizesSymmetricGaussians symmetricGaussianSchwartz := by
  exact symmetricGaussianSchwartz_apply

theorem symmetricGaussianSchwartz_nonnegative_even
    (p : PositiveGaussianIndex) :
    IsNonnegativeEvenSchwartz (symmetricGaussianSchwartz p) := by
  constructor
  · intro r
    simpa using (symmetricGaussian_pos p.1.1 p.2 r).le
  · intro r
    simpa using symmetricGaussian_even p.1.1 p.2 r

/-- Positivity of a functional on every positive-width symmetric Gaussian. -/
def GaussianFunctionalPositivity
    (W : RealSchwartz →L[ℝ] ℝ) (G : PositiveGaussianIndex → RealSchwartz) : Prop :=
  ∀ p, 0 ≤ W (G p)

/-- The precise density assertion needed by the Gaussian family: every
nonnegative even Schwartz function belongs to the closed positive cone of the
symmetric Gaussian generators. -/
def SymmetricGaussianConeDense
    (G : PositiveGaussianIndex → RealSchwartz) : Prop :=
  ∀ f, IsNonnegativeEvenSchwartz f →
    f ∈ closure (generatorCone G : Set RealSchwartz)

/-- Positivity on all symmetric Gaussians implies positivity on every
nonnegative even Schwartz test function, once the Gaussian cone density
statement is supplied. -/
theorem full_even_schwartz_positivity_of_gaussian
    (W : RealSchwartz →L[ℝ] ℝ) (G : PositiveGaussianIndex → RealSchwartz)
    (hGaussian : GaussianFunctionalPositivity W G)
    (hDense : SymmetricGaussianConeDense G) :
    ∀ f, IsNonnegativeEvenSchwartz f → 0 ≤ W f := by
  intro f hf
  exact nonnegative_on_closure_generatorCone W G hGaussian f (hDense f hf)

end

end RiemannGaussian
