import RiemannGaussian.RiemannXiSuzukiCarrierCayleyDefect

/-!
# Hardy-orbit geometry of the Cayley carrier unitary

The Cayley reduction leaves one explicit weighted synthesis.  This file
starts resolving its geometry.  The spectral Cayley parameter lies strictly
inside the unit disk for an upper-half-plane node, strictly outside for a
lower-half-plane node, and on the unit circle for a real node.  Functional-
equation partners have reciprocal Cayley parameters.

For every off-axis node, the exact unitary resolvent equation is then iterated
into finite positive- or negative-orbit geometric expansions with explicit
norm remainders.  Thus off-axis rational node features belong to the closed
cyclic Hardy subspaces generated by the canonical constant vector.  Real
nodes are deliberately left as boundary features; no radial-limit assertion
is made for them here.
-/

open Complex Filter MeasureTheory Metric Set Topology
open scoped Classical ComplexConjugate ENNReal Topology lp

namespace RiemannGaussian

noncomputable section

/-- The squared distances from `z` to the two Cayley poles differ by four
times the imaginary part. -/
theorem norm_sq_add_I_sub_norm_sq_sub_I (z : ℂ) :
    ‖z + Complex.I‖ ^ 2 - ‖z - Complex.I‖ ^ 2 = 4 * z.im := by
  rw [Complex.sq_norm, Complex.sq_norm]
  simp only [Complex.normSq_apply, add_re, add_im, sub_re, sub_im,
    Complex.I_re, Complex.I_im]
  ring

/-- The Cayley parameter is strictly contractive exactly in the upper half
plane. -/
theorem norm_suzukiXiCarrierCayleyParameter_lt_one_iff
    {z : ℂ} (hz : z + Complex.I ≠ 0) :
    ‖suzukiXiCarrierCayleyParameter z‖ < 1 ↔ 0 < z.im := by
  unfold suzukiXiCarrierCayleyParameter
  rw [norm_div, div_lt_one (norm_pos_iff.mpr hz)]
  constructor
  · intro hnorm
    have hsquared : ‖z - Complex.I‖ ^ 2 < ‖z + Complex.I‖ ^ 2 :=
      (sq_lt_sq₀ (norm_nonneg _) (norm_nonneg _)).2 hnorm
    have hdiff := norm_sq_add_I_sub_norm_sq_sub_I z
    nlinarith
  · intro him
    apply (sq_lt_sq₀ (norm_nonneg _) (norm_nonneg _)).1
    have hdiff := norm_sq_add_I_sub_norm_sq_sub_I z
    nlinarith

/-- The Cayley parameter is strictly expansive exactly in the lower half
plane. -/
theorem one_lt_norm_suzukiXiCarrierCayleyParameter_iff
    {z : ℂ} (hz : z + Complex.I ≠ 0) :
    1 < ‖suzukiXiCarrierCayleyParameter z‖ ↔ z.im < 0 := by
  unfold suzukiXiCarrierCayleyParameter
  rw [norm_div, one_lt_div (norm_pos_iff.mpr hz)]
  constructor
  · intro hnorm
    have hsquared : ‖z + Complex.I‖ ^ 2 < ‖z - Complex.I‖ ^ 2 :=
      (sq_lt_sq₀ (norm_nonneg _) (norm_nonneg _)).2 hnorm
    have hdiff := norm_sq_add_I_sub_norm_sq_sub_I z
    nlinarith
  · intro him
    apply (sq_lt_sq₀ (norm_nonneg _) (norm_nonneg _)).1
    have hdiff := norm_sq_add_I_sub_norm_sq_sub_I z
    nlinarith

/-- The Cayley parameter has unit norm exactly on the real boundary. -/
theorem norm_suzukiXiCarrierCayleyParameter_eq_one_iff
    {z : ℂ} (hz : z + Complex.I ≠ 0) :
    ‖suzukiXiCarrierCayleyParameter z‖ = 1 ↔ z.im = 0 := by
  constructor
  · intro hnorm
    by_contra him
    rcases lt_or_gt_of_ne him with him | him
    · have :=
        (one_lt_norm_suzukiXiCarrierCayleyParameter_iff hz).2 him
      linarith
    · have :=
        (norm_suzukiXiCarrierCayleyParameter_lt_one_iff hz).2 him
      linarith
  · intro him
    have hsq : ‖z - Complex.I‖ ^ 2 = ‖z + Complex.I‖ ^ 2 := by
      have hdiff := norm_sq_add_I_sub_norm_sq_sub_I z
      rw [him] at hdiff
      nlinarith
    have hnorm : ‖z - Complex.I‖ = ‖z + Complex.I‖ :=
      (sq_eq_sq₀ (norm_nonneg _) (norm_nonneg _)).1 hsq
    unfold suzukiXiCarrierCayleyParameter
    rw [norm_div, hnorm, div_self (norm_ne_zero_iff.mpr hz)]

/-- A genuine spectral-xi node is also never the other Cayley pole `i`. -/
theorem zetaSpectralCoordinate_sub_I_ne_zero
    (rho : NontrivialZetaZero) :
    zetaSpectralCoordinate rho.1 - Complex.I ≠ 0 := by
  intro hzero
  have himEq := congrArg Complex.im hzero
  have him : (zetaSpectralCoordinate rho.1).im = 1 := by
    simp only [Complex.sub_im, Complex.I_im, Complex.zero_im] at himEq
    linarith
  have hstrip := NontrivialZetaZero.abs_spectralCoordinate_im_lt_half rho
  rw [him] at hstrip
  norm_num at hstrip

/-- Negation of a nonexceptional spectral parameter becomes inversion under
the Cayley transform. -/
theorem suzukiXiCarrierCayleyParameter_neg
    (z : ℂ) (hminus : z - Complex.I ≠ 0) :
    suzukiXiCarrierCayleyParameter (-z) =
      (suzukiXiCarrierCayleyParameter z)⁻¹ := by
  have hneg : -z + Complex.I ≠ 0 := by
    intro hzero
    apply hminus
    calc
      z - Complex.I = -(-z + Complex.I) := by ring
      _ = 0 := by rw [hzero]; simp
  unfold suzukiXiCarrierCayleyParameter
  rw [inv_div]
  field_simp [hminus, hneg]
  ring

/-- Functional-equation partners have reciprocal Cayley node parameters. -/
@[simp] theorem suzukiXiCarrierCayleyNodeParameter_functionalPartner
    (rho : NontrivialZetaZero) :
    suzukiXiCarrierCayleyNodeParameter
        (NontrivialZetaZero.functionalPartner rho) =
      (suzukiXiCarrierCayleyNodeParameter rho)⁻¹ := by
  unfold suzukiXiCarrierCayleyNodeParameter
  rw [NontrivialZetaZero.spectralCoordinate_functionalPartner]
  exact suzukiXiCarrierCayleyParameter_neg _
    (zetaSpectralCoordinate_sub_I_ne_zero rho)

/-- A genuine node parameter lies in the open unit disk exactly when its
spectral coordinate lies in the upper half-plane. -/
theorem norm_suzukiXiCarrierCayleyNodeParameter_lt_one_iff
    (rho : NontrivialZetaZero) :
    ‖suzukiXiCarrierCayleyNodeParameter rho‖ < 1 ↔
      0 < (zetaSpectralCoordinate rho.1).im :=
  norm_suzukiXiCarrierCayleyParameter_lt_one_iff
    (zetaSpectralCoordinate_add_I_ne_zero rho)

/-- A genuine node parameter lies outside the closed unit disk exactly when
its spectral coordinate lies in the lower half-plane. -/
theorem one_lt_norm_suzukiXiCarrierCayleyNodeParameter_iff
    (rho : NontrivialZetaZero) :
    1 < ‖suzukiXiCarrierCayleyNodeParameter rho‖ ↔
      (zetaSpectralCoordinate rho.1).im < 0 :=
  one_lt_norm_suzukiXiCarrierCayleyParameter_iff
    (zetaSpectralCoordinate_add_I_ne_zero rho)

/-- A genuine node parameter lies on the unit circle exactly for a real
spectral coordinate. -/
theorem norm_suzukiXiCarrierCayleyNodeParameter_eq_one_iff
    (rho : NontrivialZetaZero) :
    ‖suzukiXiCarrierCayleyNodeParameter rho‖ = 1 ↔
      (zetaSpectralCoordinate rho.1).im = 0 :=
  norm_suzukiXiCarrierCayleyParameter_eq_one_iff
    (zetaSpectralCoordinate_add_I_ne_zero rho)

/-! ## Positive and negative unitary orbits -/

/-- The `n`-fold forward power of the carrier Cayley unitary, retained as a
linear equivalence so that finite sums can be transported algebraically. -/
def suzukiXiCarrierCayleyForwardPower (n : ℕ) :
    Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure ≃ₗ[ℂ]
      Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure :=
  suzukiXiCarrierCayleyUnitary.toLinearEquiv ^ n

/-- The `n`-fold backward power of the carrier Cayley unitary. -/
def suzukiXiCarrierCayleyBackwardPower (n : ℕ) :
    Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure ≃ₗ[ℂ]
      Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure :=
  suzukiXiCarrierCayleyUnitary.symm.toLinearEquiv ^ n

@[simp] theorem suzukiXiCarrierCayleyForwardPower_zero
    (f : Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure) :
    suzukiXiCarrierCayleyForwardPower 0 f = f := by
  simp [suzukiXiCarrierCayleyForwardPower]

@[simp] theorem suzukiXiCarrierCayleyBackwardPower_zero
    (f : Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure) :
    suzukiXiCarrierCayleyBackwardPower 0 f = f := by
  simp [suzukiXiCarrierCayleyBackwardPower]

/-- Successive forward powers append one application of the unitary. -/
theorem suzukiXiCarrierCayleyForwardPower_succ
    (n : ℕ) (f : Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure) :
    suzukiXiCarrierCayleyForwardPower (n + 1) f =
      suzukiXiCarrierCayleyForwardPower n
        (suzukiXiCarrierCayleyUnitary f) := by
  simp [suzukiXiCarrierCayleyForwardPower, pow_succ,
    LinearEquiv.mul_apply]

/-- Successive backward powers append one application of the inverse
unitary. -/
theorem suzukiXiCarrierCayleyBackwardPower_succ
    (n : ℕ) (f : Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure) :
    suzukiXiCarrierCayleyBackwardPower (n + 1) f =
      suzukiXiCarrierCayleyBackwardPower n
        (suzukiXiCarrierCayleyUnitary.symm f) := by
  simp [suzukiXiCarrierCayleyBackwardPower, pow_succ,
    LinearEquiv.mul_apply]

/-- Every forward power remains an isometry. -/
@[simp] theorem norm_suzukiXiCarrierCayleyForwardPower
    (n : ℕ) (f : Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure) :
    ‖suzukiXiCarrierCayleyForwardPower n f‖ = ‖f‖ := by
  induction n generalizing f with
  | zero => simp
  | succ n ih =>
      rw [suzukiXiCarrierCayleyForwardPower_succ, ih,
        suzukiXiCarrierCayleyUnitary.norm_map]

/-- Every backward power remains an isometry. -/
@[simp] theorem norm_suzukiXiCarrierCayleyBackwardPower
    (n : ℕ) (f : Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure) :
    ‖suzukiXiCarrierCayleyBackwardPower n f‖ = ‖f‖ := by
  induction n generalizing f with
  | zero => simp
  | succ n ih =>
      rw [suzukiXiCarrierCayleyBackwardPower_succ, ih,
        suzukiXiCarrierCayleyUnitary.symm.norm_map]

/-- The nonnegative forward orbit generated by the constant vector. -/
def suzukiXiCarrierCayleyForwardOrbit (n : ℕ) :
    Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure :=
  suzukiXiCarrierCayleyForwardPower (n + 1)
    suzukiXiCarrierNevanlinnaOneLp

/-- The nonpositive backward orbit generated by the constant vector. -/
def suzukiXiCarrierCayleyBackwardOrbit (n : ℕ) :
    Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure :=
  suzukiXiCarrierCayleyBackwardPower n suzukiXiCarrierNevanlinnaOneLp

/-- The finite backward-orbit geometric approximation with parameter `a`. -/
def suzukiXiCarrierCayleyBackwardGeometricApproximation
    (a : ℂ) (n : ℕ) : Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure :=
  ∑ k ∈ Finset.range n,
    ((1 - a) * a ^ k) • suzukiXiCarrierCayleyBackwardOrbit k

/-- The finite forward-orbit geometric approximation with reciprocal
parameter `a⁻¹`. -/
def suzukiXiCarrierCayleyForwardGeometricApproximation
    (a : ℂ) (n : ℕ) : Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure :=
  ∑ k ∈ Finset.range n,
    ((1 - a⁻¹) * (a⁻¹) ^ k) • suzukiXiCarrierCayleyForwardOrbit k

/-- The inverse-unitary node equation transported through `n` backward
powers. -/
theorem suzukiXiCarrierCayleyBackwardPower_node_resolvent
    (rho : NontrivialZetaZero) (n : ℕ) :
    suzukiXiCarrierCayleyBackwardPower n
        (suzukiXiCarrierNevanlinnaNodeFeatureLp rho) -
      suzukiXiCarrierCayleyNodeParameter rho •
        suzukiXiCarrierCayleyBackwardPower (n + 1)
          (suzukiXiCarrierNevanlinnaNodeFeatureLp rho) =
      (1 - suzukiXiCarrierCayleyNodeParameter rho) •
        suzukiXiCarrierCayleyBackwardOrbit n := by
  have h := congrArg
    (fun f : Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure ↦
      suzukiXiCarrierCayleyBackwardPower n f)
    (suzukiXiCarrierCayleyUnitary_symm_nodeFeature_resolvent rho)
  simpa only [map_sub, map_smul,
    suzukiXiCarrierCayleyBackwardPower_succ,
    suzukiXiCarrierCayleyBackwardOrbit] using h

/-- Exact finite backward-orbit expansion of every genuine node feature. -/
theorem suzukiXiCarrierNevanlinnaNodeFeatureLp_eq_backwardApproximation_add
    (rho : NontrivialZetaZero) (n : ℕ) :
    suzukiXiCarrierNevanlinnaNodeFeatureLp rho =
      suzukiXiCarrierCayleyBackwardGeometricApproximation
          (suzukiXiCarrierCayleyNodeParameter rho) n +
        (suzukiXiCarrierCayleyNodeParameter rho) ^ n •
          suzukiXiCarrierCayleyBackwardPower n
            (suzukiXiCarrierNevanlinnaNodeFeatureLp rho) := by
  induction n with
  | zero =>
      simp [suzukiXiCarrierCayleyBackwardGeometricApproximation]
  | succ n ih =>
      let a : ℂ := suzukiXiCarrierCayleyNodeParameter rho
      let F : Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure :=
        suzukiXiCarrierNevanlinnaNodeFeatureLp rho
      have hrecurrence :
          suzukiXiCarrierCayleyBackwardPower n F =
            (1 - a) • suzukiXiCarrierCayleyBackwardOrbit n +
              a • suzukiXiCarrierCayleyBackwardPower (n + 1) F := by
        exact (sub_eq_iff_eq_add).mp
          (suzukiXiCarrierCayleyBackwardPower_node_resolvent rho n)
      calc
        F = suzukiXiCarrierCayleyBackwardGeometricApproximation a n +
            a ^ n • suzukiXiCarrierCayleyBackwardPower n F := ih
        _ = suzukiXiCarrierCayleyBackwardGeometricApproximation a (n + 1) +
            a ^ (n + 1) •
              suzukiXiCarrierCayleyBackwardPower (n + 1) F := by
          rw [hrecurrence]
          unfold suzukiXiCarrierCayleyBackwardGeometricApproximation
          rw [Finset.sum_range_succ, pow_succ]
          simp only [smul_add, smul_smul]
          module

/-- Exact norm of the remainder in the finite backward-orbit expansion. -/
theorem norm_sub_suzukiXiCarrierCayleyBackwardGeometricApproximation
    (rho : NontrivialZetaZero) (n : ℕ) :
    ‖suzukiXiCarrierNevanlinnaNodeFeatureLp rho -
        suzukiXiCarrierCayleyBackwardGeometricApproximation
          (suzukiXiCarrierCayleyNodeParameter rho) n‖ =
      ‖suzukiXiCarrierCayleyNodeParameter rho‖ ^ n *
        ‖suzukiXiCarrierNevanlinnaNodeFeatureLp rho‖ := by
  rw [(sub_eq_iff_eq_add').2
    (suzukiXiCarrierNevanlinnaNodeFeatureLp_eq_backwardApproximation_add
      rho n)]
  rw [norm_smul, norm_pow,
    norm_suzukiXiCarrierCayleyBackwardPower]

/-- For an upper-half-plane spectral node, the backward-orbit geometric
approximations converge in `L²(μ)` to its rational feature. -/
theorem tendsto_suzukiXiCarrierCayleyBackwardGeometricApproximation
    (rho : NontrivialZetaZero)
    (hupper : 0 < (zetaSpectralCoordinate rho.1).im) :
    Tendsto (fun n : ℕ ↦
      suzukiXiCarrierCayleyBackwardGeometricApproximation
        (suzukiXiCarrierCayleyNodeParameter rho) n) atTop
      (nhds (suzukiXiCarrierNevanlinnaNodeFeatureLp rho)) := by
  rw [tendsto_iff_norm_sub_tendsto_zero]
  have hparameter : ‖suzukiXiCarrierCayleyNodeParameter rho‖ < 1 :=
    (norm_suzukiXiCarrierCayleyNodeParameter_lt_one_iff rho).2 hupper
  have hpow :=
    (tendsto_pow_atTop_nhds_zero_of_lt_one
      (norm_nonneg (suzukiXiCarrierCayleyNodeParameter rho))
      hparameter).mul_const
        ‖suzukiXiCarrierNevanlinnaNodeFeatureLp rho‖
  have hpow' : Tendsto (fun n : ℕ ↦
      ‖suzukiXiCarrierCayleyNodeParameter rho‖ ^ n *
        ‖suzukiXiCarrierNevanlinnaNodeFeatureLp rho‖) atTop (nhds 0) := by
    simpa only [zero_mul] using hpow
  refine hpow'.congr' ?_
  exact Eventually.of_forall fun n ↦ by
    change ‖suzukiXiCarrierCayleyNodeParameter rho‖ ^ n *
        ‖suzukiXiCarrierNevanlinnaNodeFeatureLp rho‖ =
      ‖suzukiXiCarrierCayleyBackwardGeometricApproximation
          (suzukiXiCarrierCayleyNodeParameter rho) n -
        suzukiXiCarrierNevanlinnaNodeFeatureLp rho‖
    rw [norm_sub_rev,
      norm_sub_suzukiXiCarrierCayleyBackwardGeometricApproximation]

/-- The closed cyclic subspace generated by nonpositive powers of the Cayley
unitary applied to the constant vector. -/
def suzukiXiCarrierCayleyBackwardHardySubmodule :
    Submodule ℂ (Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure) :=
  (Submodule.span ℂ (Set.range suzukiXiCarrierCayleyBackwardOrbit)).topologicalClosure

/-- Every finite backward geometric approximation belongs to the algebraic
span defining the backward Hardy submodule. -/
theorem suzukiXiCarrierCayleyBackwardGeometricApproximation_mem_span
    (a : ℂ) (n : ℕ) :
    suzukiXiCarrierCayleyBackwardGeometricApproximation a n ∈
      Submodule.span ℂ (Set.range suzukiXiCarrierCayleyBackwardOrbit) := by
  unfold suzukiXiCarrierCayleyBackwardGeometricApproximation
  apply Submodule.sum_mem
  intro k _hk
  exact Submodule.smul_mem _ _
    (Submodule.subset_span (Set.mem_range_self k))

/-- Every upper-half-plane genuine node feature lies in the closed backward
cyclic Hardy subspace. -/
theorem suzukiXiCarrierNevanlinnaNodeFeatureLp_mem_backwardHardySubmodule
    (rho : NontrivialZetaZero)
    (hupper : 0 < (zetaSpectralCoordinate rho.1).im) :
    suzukiXiCarrierNevanlinnaNodeFeatureLp rho ∈
      suzukiXiCarrierCayleyBackwardHardySubmodule := by
  apply (Submodule.isClosed_topologicalClosure
    (Submodule.span ℂ
      (Set.range suzukiXiCarrierCayleyBackwardOrbit))).mem_of_tendsto
      (tendsto_suzukiXiCarrierCayleyBackwardGeometricApproximation rho hupper)
  exact Eventually.of_forall fun n ↦
    Submodule.le_topologicalClosure _
      (suzukiXiCarrierCayleyBackwardGeometricApproximation_mem_span
        (suzukiXiCarrierCayleyNodeParameter rho) n)

/-! ## Forward expansion for lower-half-plane nodes -/

/-- Every genuine Cayley node parameter is nonzero. -/
theorem suzukiXiCarrierCayleyNodeParameter_ne_zero
    (rho : NontrivialZetaZero) :
    suzukiXiCarrierCayleyNodeParameter rho ≠ 0 := by
  unfold suzukiXiCarrierCayleyNodeParameter
    suzukiXiCarrierCayleyParameter
  exact div_ne_zero (zetaSpectralCoordinate_sub_I_ne_zero rho)
    (zetaSpectralCoordinate_add_I_ne_zero rho)

/-- Solving the node equation in the expansive direction replaces the
parameter by its reciprocal and exposes the first positive unitary orbit. -/
theorem suzukiXiCarrierCayleyUnitary_nodeFeature_forward_resolvent
    (rho : NontrivialZetaZero) :
    suzukiXiCarrierNevanlinnaNodeFeatureLp rho -
      (suzukiXiCarrierCayleyNodeParameter rho)⁻¹ •
        suzukiXiCarrierCayleyUnitary
          (suzukiXiCarrierNevanlinnaNodeFeatureLp rho) =
      (1 - (suzukiXiCarrierCayleyNodeParameter rho)⁻¹) •
        suzukiXiCarrierCayleyUnitary
          suzukiXiCarrierNevanlinnaOneLp := by
  let a : ℂ := suzukiXiCarrierCayleyNodeParameter rho
  let F : Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure :=
    suzukiXiCarrierNevanlinnaNodeFeatureLp rho
  let Uone : Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure :=
    suzukiXiCarrierCayleyUnitary suzukiXiCarrierNevanlinnaOneLp
  have ha : a ≠ 0 := suzukiXiCarrierCayleyNodeParameter_ne_zero rho
  have hnode :
      suzukiXiCarrierCayleyUnitary F - a • F = (1 - a) • Uone := by
    exact suzukiXiCarrierCayleyUnitary_nodeFeature_resolvent rho
  calc
    F - a⁻¹ • suzukiXiCarrierCayleyUnitary F =
        (-a⁻¹) • (suzukiXiCarrierCayleyUnitary F - a • F) := by
      rw [smul_sub, smul_smul, neg_mul, inv_mul_cancel₀ ha,
        neg_one_smul]
      module
    _ = (-a⁻¹) • ((1 - a) • Uone) :=
      congrArg (fun f ↦ (-a⁻¹) • f) hnode
    _ = (1 - a⁻¹) • Uone := by
      rw [smul_smul]
      congr 1
      field_simp [ha]
      ring

/-- The forward node equation transported through `n` unitary powers. -/
theorem suzukiXiCarrierCayleyForwardPower_node_resolvent
    (rho : NontrivialZetaZero) (n : ℕ) :
    suzukiXiCarrierCayleyForwardPower n
        (suzukiXiCarrierNevanlinnaNodeFeatureLp rho) -
      (suzukiXiCarrierCayleyNodeParameter rho)⁻¹ •
        suzukiXiCarrierCayleyForwardPower (n + 1)
          (suzukiXiCarrierNevanlinnaNodeFeatureLp rho) =
      (1 - (suzukiXiCarrierCayleyNodeParameter rho)⁻¹) •
        suzukiXiCarrierCayleyForwardOrbit n := by
  have h := congrArg
    (fun f : Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure ↦
      suzukiXiCarrierCayleyForwardPower n f)
    (suzukiXiCarrierCayleyUnitary_nodeFeature_forward_resolvent rho)
  simpa only [map_sub, map_smul,
    suzukiXiCarrierCayleyForwardPower_succ,
    suzukiXiCarrierCayleyForwardOrbit] using h

/-- Exact finite forward-orbit expansion of every genuine node feature. -/
theorem suzukiXiCarrierNevanlinnaNodeFeatureLp_eq_forwardApproximation_add
    (rho : NontrivialZetaZero) (n : ℕ) :
    suzukiXiCarrierNevanlinnaNodeFeatureLp rho =
      suzukiXiCarrierCayleyForwardGeometricApproximation
          (suzukiXiCarrierCayleyNodeParameter rho) n +
        ((suzukiXiCarrierCayleyNodeParameter rho)⁻¹) ^ n •
          suzukiXiCarrierCayleyForwardPower n
            (suzukiXiCarrierNevanlinnaNodeFeatureLp rho) := by
  induction n with
  | zero =>
      simp [suzukiXiCarrierCayleyForwardGeometricApproximation]
  | succ n ih =>
      let a : ℂ := suzukiXiCarrierCayleyNodeParameter rho
      let F : Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure :=
        suzukiXiCarrierNevanlinnaNodeFeatureLp rho
      have hrecurrence :
          suzukiXiCarrierCayleyForwardPower n F =
            (1 - a⁻¹) • suzukiXiCarrierCayleyForwardOrbit n +
              a⁻¹ • suzukiXiCarrierCayleyForwardPower (n + 1) F := by
        exact (sub_eq_iff_eq_add).mp
          (suzukiXiCarrierCayleyForwardPower_node_resolvent rho n)
      calc
        F = suzukiXiCarrierCayleyForwardGeometricApproximation a n +
            (a⁻¹) ^ n • suzukiXiCarrierCayleyForwardPower n F := ih
        _ = suzukiXiCarrierCayleyForwardGeometricApproximation a (n + 1) +
            (a⁻¹) ^ (n + 1) •
              suzukiXiCarrierCayleyForwardPower (n + 1) F := by
          rw [hrecurrence]
          unfold suzukiXiCarrierCayleyForwardGeometricApproximation
          rw [Finset.sum_range_succ, pow_succ]
          simp only [smul_add, smul_smul]
          module

/-- Exact norm of the remainder in the finite forward-orbit expansion. -/
theorem norm_sub_suzukiXiCarrierCayleyForwardGeometricApproximation
    (rho : NontrivialZetaZero) (n : ℕ) :
    ‖suzukiXiCarrierNevanlinnaNodeFeatureLp rho -
        suzukiXiCarrierCayleyForwardGeometricApproximation
          (suzukiXiCarrierCayleyNodeParameter rho) n‖ =
      ‖(suzukiXiCarrierCayleyNodeParameter rho)⁻¹‖ ^ n *
        ‖suzukiXiCarrierNevanlinnaNodeFeatureLp rho‖ := by
  rw [(sub_eq_iff_eq_add').2
    (suzukiXiCarrierNevanlinnaNodeFeatureLp_eq_forwardApproximation_add
      rho n)]
  rw [norm_smul, norm_pow,
    norm_suzukiXiCarrierCayleyForwardPower]

/-- For a lower-half-plane spectral node, the forward-orbit geometric
approximations converge in `L²(μ)` to its rational feature. -/
theorem tendsto_suzukiXiCarrierCayleyForwardGeometricApproximation
    (rho : NontrivialZetaZero)
    (hlower : (zetaSpectralCoordinate rho.1).im < 0) :
    Tendsto (fun n : ℕ ↦
      suzukiXiCarrierCayleyForwardGeometricApproximation
        (suzukiXiCarrierCayleyNodeParameter rho) n) atTop
      (nhds (suzukiXiCarrierNevanlinnaNodeFeatureLp rho)) := by
  rw [tendsto_iff_norm_sub_tendsto_zero]
  have hparameter : 1 < ‖suzukiXiCarrierCayleyNodeParameter rho‖ :=
    (one_lt_norm_suzukiXiCarrierCayleyNodeParameter_iff rho).2 hlower
  have hinverse :
      ‖(suzukiXiCarrierCayleyNodeParameter rho)⁻¹‖ < 1 := by
    rw [norm_inv]
    exact inv_lt_one_of_one_lt₀ hparameter
  have hpow :=
    (tendsto_pow_atTop_nhds_zero_of_lt_one
      (norm_nonneg ((suzukiXiCarrierCayleyNodeParameter rho)⁻¹))
      hinverse).mul_const
        ‖suzukiXiCarrierNevanlinnaNodeFeatureLp rho‖
  have hpow' : Tendsto (fun n : ℕ ↦
      ‖(suzukiXiCarrierCayleyNodeParameter rho)⁻¹‖ ^ n *
        ‖suzukiXiCarrierNevanlinnaNodeFeatureLp rho‖) atTop (nhds 0) := by
    simpa only [zero_mul] using hpow
  refine hpow'.congr' ?_
  exact Eventually.of_forall fun n ↦ by
    change ‖(suzukiXiCarrierCayleyNodeParameter rho)⁻¹‖ ^ n *
        ‖suzukiXiCarrierNevanlinnaNodeFeatureLp rho‖ =
      ‖suzukiXiCarrierCayleyForwardGeometricApproximation
          (suzukiXiCarrierCayleyNodeParameter rho) n -
        suzukiXiCarrierNevanlinnaNodeFeatureLp rho‖
    rw [norm_sub_rev,
      norm_sub_suzukiXiCarrierCayleyForwardGeometricApproximation]

/-- The closed cyclic subspace generated by strictly positive powers of the
Cayley unitary applied to the constant vector. -/
def suzukiXiCarrierCayleyForwardHardySubmodule :
    Submodule ℂ (Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure) :=
  (Submodule.span ℂ (Set.range suzukiXiCarrierCayleyForwardOrbit)).topologicalClosure

/-- Every finite forward geometric approximation belongs to the algebraic
span defining the forward Hardy submodule. -/
theorem suzukiXiCarrierCayleyForwardGeometricApproximation_mem_span
    (a : ℂ) (n : ℕ) :
    suzukiXiCarrierCayleyForwardGeometricApproximation a n ∈
      Submodule.span ℂ (Set.range suzukiXiCarrierCayleyForwardOrbit) := by
  unfold suzukiXiCarrierCayleyForwardGeometricApproximation
  apply Submodule.sum_mem
  intro k _hk
  exact Submodule.smul_mem _ _
    (Submodule.subset_span (Set.mem_range_self k))

/-- Every lower-half-plane genuine node feature lies in the closed forward
cyclic Hardy subspace. -/
theorem suzukiXiCarrierNevanlinnaNodeFeatureLp_mem_forwardHardySubmodule
    (rho : NontrivialZetaZero)
    (hlower : (zetaSpectralCoordinate rho.1).im < 0) :
    suzukiXiCarrierNevanlinnaNodeFeatureLp rho ∈
      suzukiXiCarrierCayleyForwardHardySubmodule := by
  apply (Submodule.isClosed_topologicalClosure
    (Submodule.span ℂ
      (Set.range suzukiXiCarrierCayleyForwardOrbit))).mem_of_tendsto
      (tendsto_suzukiXiCarrierCayleyForwardGeometricApproximation rho hlower)
  exact Eventually.of_forall fun n ↦
    Submodule.le_topologicalClosure _
      (suzukiXiCarrierCayleyForwardGeometricApproximation_mem_span
        (suzukiXiCarrierCayleyNodeParameter rho) n)

/-! ## The off-axis Hardy split -/

/-- The closed sum of the positive and negative cyclic Hardy subspaces. -/
def suzukiXiCarrierCayleyOffAxisHardySubmodule :
    Submodule ℂ (Lp ℂ 2 suzukiXiCarrierNevanlinnaMeasure) :=
  suzukiXiCarrierCayleyForwardHardySubmodule ⊔
    suzukiXiCarrierCayleyBackwardHardySubmodule

/-- Every genuine off-axis node feature belongs to the closed sum of the two
opposite cyclic Hardy subspaces. -/
theorem suzukiXiCarrierNevanlinnaNodeFeatureLp_mem_offAxisHardySubmodule
    (rho : NontrivialZetaZero)
    (hoffAxis : (zetaSpectralCoordinate rho.1).im ≠ 0) :
    suzukiXiCarrierNevanlinnaNodeFeatureLp rho ∈
      suzukiXiCarrierCayleyOffAxisHardySubmodule := by
  rcases lt_or_gt_of_ne hoffAxis with hlower | hupper
  · exact (show suzukiXiCarrierCayleyForwardHardySubmodule ≤
        suzukiXiCarrierCayleyOffAxisHardySubmodule from le_sup_left)
      (suzukiXiCarrierNevanlinnaNodeFeatureLp_mem_forwardHardySubmodule
        rho hlower)
  · exact (show suzukiXiCarrierCayleyBackwardHardySubmodule ≤
        suzukiXiCarrierCayleyOffAxisHardySubmodule from le_sup_right)
      (suzukiXiCarrierNevanlinnaNodeFeatureLp_mem_backwardHardySubmodule
        rho hupper)

/-- Functional-equation partners of upper nodes land in the forward Hardy
subspace, matching reciprocal Cayley parameters. -/
theorem functionalPartner_nodeFeatureLp_mem_forwardHardySubmodule
    (rho : NontrivialZetaZero)
    (hupper : 0 < (zetaSpectralCoordinate rho.1).im) :
    suzukiXiCarrierNevanlinnaNodeFeatureLp
        (NontrivialZetaZero.functionalPartner rho) ∈
      suzukiXiCarrierCayleyForwardHardySubmodule := by
  apply suzukiXiCarrierNevanlinnaNodeFeatureLp_mem_forwardHardySubmodule
  rw [NontrivialZetaZero.spectralCoordinate_functionalPartner]
  simpa using neg_lt_zero.mpr hupper

/-- Functional-equation partners of lower nodes land in the backward Hardy
subspace. -/
theorem functionalPartner_nodeFeatureLp_mem_backwardHardySubmodule
    (rho : NontrivialZetaZero)
    (hlower : (zetaSpectralCoordinate rho.1).im < 0) :
    suzukiXiCarrierNevanlinnaNodeFeatureLp
        (NontrivialZetaZero.functionalPartner rho) ∈
      suzukiXiCarrierCayleyBackwardHardySubmodule := by
  apply suzukiXiCarrierNevanlinnaNodeFeatureLp_mem_backwardHardySubmodule
  rw [NontrivialZetaZero.spectralCoordinate_functionalPartner]
  simpa using neg_pos.mpr hlower

/-- Any finite Cayley-weighted synthesis supported away from real spectral
nodes belongs to the off-axis Hardy sum. -/
theorem suzukiXiCarrierNevanlinnaCayleyWeightedFiniteSynthesis_mem_offAxisHardy
    (c : NontrivialZetaZero →₀ ℂ)
    (hoffAxis : ∀ rho ∈ c.support,
      (zetaSpectralCoordinate rho.1).im ≠ 0) :
    suzukiXiCarrierNevanlinnaCayleyWeightedFiniteSynthesis c ∈
      suzukiXiCarrierCayleyOffAxisHardySubmodule := by
  unfold suzukiXiCarrierNevanlinnaCayleyWeightedFiniteSynthesis
  apply Submodule.sum_mem
  intro rho hrho
  exact Submodule.smul_mem _ _
    (suzukiXiCarrierNevanlinnaNodeFeatureLp_mem_offAxisHardySubmodule
      rho (hoffAxis rho hrho))

end

end RiemannGaussian
