import RiemannGaussian.RiemannXiSuzukiPositiveCriticalStripEtaCompletedGaussianCoupling
import RiemannGaussian.RiemannXiSuzukiPositiveCriticalStripEtaFiniteGaussianLaplaceGram

/-!
# Infinite positive eta Gaussian--Laplace Gram identity

The finite eta Gram theorem already identifies Gaussian vertical averages of
finite positive-Laplace partitions with a positive double kernel.  The exact
completed symmetry, however, belongs to the fixed infinite eta measure.  This
module closes that mismatch directly.

For every positive horizontal tilt and positive Gaussian time, it proves all
integrability and Fubini obligations for the infinite measure and identifies
the raw Gaussian norm with the same explicit positive double kernel used at
finite level.  It then compares this raw Gram object with the newly completed
energy, exposing the ordinate-dependent completion weight as the remaining
symmetry distortion.
-/

open Complex Filter MeasureTheory Metric Set Topology
open scoped Classical ComplexConjugate ENNReal Interval Topology

namespace RiemannGaussian

noncomputable section

/-- The fixed infinite eta logarithmic measure is sigma-finite. -/
instance pairedEtaLogMeasure.instSFinite : SFinite pairedEtaLogMeasure := by
  unfold pairedEtaLogMeasure
  infer_instance

/-- The real exponential tilt is integrable against the fixed infinite eta
measure for every positive horizontal parameter. -/
theorem integrable_rexp_neg_mul_pairedEtaLogMeasure
    {sigma : ℝ} (hsigma : 0 < sigma) :
    Integrable (fun t : ℝ ↦ Real.exp (-sigma * t))
      pairedEtaLogMeasure := by
  simpa using integrable_pairedEtaTiltedCosineKernel sigma 0 hsigma

/-- Gaussian vertical-line norm of the fixed infinite positive eta Laplace
partition. -/
def pairedEtaGaussianLaplaceNorm (sigma tau : ℝ) : ℝ :=
  ∫ y : ℝ, translatedGaussian tau 0 y *
    Complex.normSq (pairedEtaLaplacePartition
      ((sigma : ℂ) + (y : ℂ) * Complex.I))

/-- The infinite positive double-measure Gram form generated by the same
kernel as the finite eta Gaussian identity. -/
def pairedEtaGaussianLaplaceGram (sigma tau : ℝ) : ℝ :=
  Real.sqrt (Real.pi / tau) *
    ∫ p : ℝ × ℝ, pairedEtaFiniteGaussianLaplaceKernel sigma tau p
      ∂pairedEtaLogMeasure.prod pairedEtaLogMeasure

private def pairedEtaGaussianLaplaceJoint
    (sigma tau : ℝ) (z : ℝ × (ℝ × ℝ)) : ℂ :=
  (Real.exp (-sigma * (z.2.1 + z.2.2)) : ℂ) *
    complexTranslatedGaussianOscillation tau 0
      (z.2.2 - z.2.1) z.1

private theorem pairedEtaGaussianLaplaceJoint_eq_laplaceProduct
    (sigma tau y t u : ℝ) :
    pairedEtaGaussianLaplaceJoint sigma tau (y, (t, u)) =
      (translatedGaussian tau 0 y : ℂ) *
        Complex.exp
          (-((sigma : ℂ) + (y : ℂ) * Complex.I) * t) *
        starRingEnd ℂ
          (Complex.exp
            (-((sigma : ℂ) + (y : ℂ) * Complex.I) * u)) := by
  unfold pairedEtaGaussianLaplaceJoint
    complexTranslatedGaussianOscillation translatedGaussian
  rw [Complex.ofReal_exp, Complex.ofReal_exp, ← Complex.exp_conj]
  simp only [map_neg, map_mul, map_add, Complex.conj_ofReal,
    Complex.conj_I, neg_mul]
  rw [← Complex.exp_add, ← Complex.exp_add, ← Complex.exp_add]
  congr 1
  push_cast
  ring

private theorem integrable_pairedEtaGaussianLaplaceJoint
    {sigma tau : ℝ} (hsigma : 0 < sigma) (htau : 0 < tau) :
    Integrable (pairedEtaGaussianLaplaceJoint sigma tau)
      (volume.prod (pairedEtaLogMeasure.prod pairedEtaLogMeasure)) := by
  have hy := integrable_translatedGaussian htau 0
  have hsigmaInt :=
    integrable_rexp_neg_mul_pairedEtaLogMeasure hsigma
  have hmajor := hy.mul_prod (hsigmaInt.mul_prod hsigmaInt)
  apply hmajor.mono
  · exact (show Continuous
      (pairedEtaGaussianLaplaceJoint sigma tau) by
        unfold pairedEtaGaussianLaplaceJoint
          complexTranslatedGaussianOscillation
        fun_prop).aestronglyMeasurable
  · exact Eventually.of_forall fun z => by
      apply le_of_eq
      unfold pairedEtaGaussianLaplaceJoint
        complexTranslatedGaussianOscillation translatedGaussian
      simp only [norm_mul, Complex.norm_real, Real.norm_eq_abs,
        abs_of_pos (Real.exp_pos _), Complex.norm_exp,
        Complex.add_re, Complex.ofReal_re, Complex.mul_re,
        Complex.I_re, Complex.I_im, Complex.ofReal_im,
        mul_zero, zero_mul, sub_zero]
      norm_num [Complex.mul_im]
      rw [← Real.exp_add, ← Real.exp_add, ← Real.exp_add]
      congr 1
      ring

private theorem integral_pairedEtaGaussianLaplaceJoint_prod
    {sigma : ℝ} (hsigma : 0 < sigma) (tau y : ℝ) :
    (∫ p : ℝ × ℝ,
        pairedEtaGaussianLaplaceJoint sigma tau (y, p)
        ∂(pairedEtaLogMeasure.prod pairedEtaLogMeasure)) =
      (translatedGaussian tau 0 y : ℂ) *
        pairedEtaLaplacePartition
          ((sigma : ℂ) + (y : ℂ) * Complex.I) *
        starRingEnd ℂ
          (pairedEtaLaplacePartition
            ((sigma : ℂ) + (y : ℂ) * Complex.I)) := by
  have hline : 0 < ((sigma : ℂ) + (y : ℂ) * Complex.I).re := by
    norm_num
    exact hsigma
  rw [show
    (fun p : ℝ × ℝ ↦
      pairedEtaGaussianLaplaceJoint sigma tau (y, p)) =
      (fun p : ℝ × ℝ ↦
        (translatedGaussian tau 0 y : ℂ) *
          (Complex.exp
              (-((sigma : ℂ) + (y : ℂ) * Complex.I) * p.1) *
            starRingEnd ℂ
              (Complex.exp
                (-((sigma : ℂ) + (y : ℂ) * Complex.I) * p.2)))) by
      funext p
      rw [pairedEtaGaussianLaplaceJoint_eq_laplaceProduct]
      ring]
  rw [integral_const_mul]
  rw [integral_prod_mul
    (μ := pairedEtaLogMeasure)
    (ν := pairedEtaLogMeasure)
    (fun t : ℝ ↦ Complex.exp
      (-((sigma : ℂ) + (y : ℂ) * Complex.I) * t))
    (fun u : ℝ ↦ starRingEnd ℂ (Complex.exp
      (-((sigma : ℂ) + (y : ℂ) * Complex.I) * u)))]
  rw [integral_conj]
  rw [integral_exp_neg_mul_pairedEtaLogMeasure_eq_laplacePartition hline]
  ring

private theorem integral_pairedEtaGaussianLaplaceJoint_volume
    (sigma : ℝ) {tau : ℝ} (htau : 0 < tau) (p : ℝ × ℝ) :
    (∫ y : ℝ,
        pairedEtaGaussianLaplaceJoint sigma tau (y, p)) =
      (Real.sqrt (Real.pi / tau) : ℂ) *
        (pairedEtaFiniteGaussianLaplaceKernel sigma tau p : ℂ) := by
  unfold pairedEtaGaussianLaplaceJoint
  change (∫ y : ℝ,
      (Real.exp (-sigma * (p.1 + p.2)) : ℂ) *
        complexTranslatedGaussianOscillation tau 0
          (p.2 - p.1) y) = _
  rw [integral_const_mul,
    integral_complexTranslatedGaussianOscillation htau]
  unfold pairedEtaFiniteGaussianLaplaceKernel
  norm_num
  ring_nf

/-- The Gaussian norm of the fixed infinite positive eta partition is
genuinely integrable for every positive horizontal tilt and Gaussian time. -/
theorem integrable_pairedEtaGaussianLaplaceNorm
    {sigma tau : ℝ} (hsigma : 0 < sigma) (htau : 0 < tau) :
    Integrable (fun y : ℝ ↦ translatedGaussian tau 0 y *
      Complex.normSq (pairedEtaLaplacePartition
        ((sigma : ℂ) + (y : ℂ) * Complex.I))) := by
  have hjoint :=
    integrable_pairedEtaGaussianLaplaceJoint hsigma htau
  have houter := hjoint.integral_prod_left
  have hcomplex : Integrable (fun y : ℝ ↦
      ((translatedGaussian tau 0 y *
        Complex.normSq (pairedEtaLaplacePartition
          ((sigma : ℂ) + (y : ℂ) * Complex.I)) : ℝ) : ℂ)) := by
    apply houter.congr
    exact Eventually.of_forall fun y => by
      change (∫ p : ℝ × ℝ,
          pairedEtaGaussianLaplaceJoint sigma tau (y, p)
          ∂(pairedEtaLogMeasure.prod pairedEtaLogMeasure)) =
        ((translatedGaussian tau 0 y *
          Complex.normSq (pairedEtaLaplacePartition
            ((sigma : ℂ) + (y : ℂ) * Complex.I)) : ℝ) : ℂ)
      rw [integral_pairedEtaGaussianLaplaceJoint_prod hsigma]
      push_cast
      rw [Complex.normSq_eq_conj_mul_self]
      ring
  have hre := hcomplex.re
  rw [RCLike.re_eq_complex_re] at hre
  simpa using hre

/-- Exact positive Gaussian--Laplace Gram identity for the fixed infinite eta
partition. -/
theorem pairedEtaGaussianLaplaceNorm_eq_gram
    {sigma tau : ℝ} (hsigma : 0 < sigma) (htau : 0 < tau) :
    pairedEtaGaussianLaplaceNorm sigma tau =
      pairedEtaGaussianLaplaceGram sigma tau := by
  apply Complex.ofReal_injective
  have hjoint :=
    integrable_pairedEtaGaussianLaplaceJoint hsigma htau
  calc
    (pairedEtaGaussianLaplaceNorm sigma tau : ℂ) =
        ∫ y : ℝ, ∫ p : ℝ × ℝ,
          pairedEtaGaussianLaplaceJoint sigma tau (y, p)
          ∂(pairedEtaLogMeasure.prod pairedEtaLogMeasure) := by
      unfold pairedEtaGaussianLaplaceNorm
      rw [← integral_complex_ofReal]
      apply integral_congr_ae
      exact Eventually.of_forall fun y => by
        change ((translatedGaussian tau 0 y *
            Complex.normSq (pairedEtaLaplacePartition
              ((sigma : ℂ) + (y : ℂ) * Complex.I)) : ℝ) : ℂ) =
          ∫ p : ℝ × ℝ,
            pairedEtaGaussianLaplaceJoint sigma tau (y, p)
            ∂(pairedEtaLogMeasure.prod pairedEtaLogMeasure)
        rw [integral_pairedEtaGaussianLaplaceJoint_prod hsigma]
        push_cast
        rw [Complex.normSq_eq_conj_mul_self]
        ring
    _ = ∫ z : ℝ × (ℝ × ℝ),
          pairedEtaGaussianLaplaceJoint sigma tau z
          ∂volume.prod (pairedEtaLogMeasure.prod pairedEtaLogMeasure) := by
      exact integral_integral hjoint
    _ = ∫ p : ℝ × ℝ, ∫ y : ℝ,
          pairedEtaGaussianLaplaceJoint sigma tau (y, p)
          ∂volume
          ∂(pairedEtaLogMeasure.prod pairedEtaLogMeasure) := by
      exact integral_prod_symm _ hjoint
    _ = ∫ p : ℝ × ℝ,
          (Real.sqrt (Real.pi / tau) : ℂ) *
            (pairedEtaFiniteGaussianLaplaceKernel sigma tau p : ℂ)
          ∂(pairedEtaLogMeasure.prod pairedEtaLogMeasure) := by
      apply integral_congr_ae
      exact Eventually.of_forall fun p =>
        integral_pairedEtaGaussianLaplaceJoint_volume sigma htau p
    _ = (pairedEtaGaussianLaplaceGram sigma tau : ℂ) := by
      unfold pairedEtaGaussianLaplaceGram
      rw [integral_const_mul, integral_complex_ofReal]
      push_cast
      rfl

/-- The positive Gaussian--Laplace kernel is integrable over the product of
the fixed infinite eta measure with itself. -/
theorem integrable_pairedEtaGaussianLaplaceKernel
    {sigma tau : ℝ} (hsigma : 0 < sigma) (htau : 0 < tau) :
    Integrable (pairedEtaFiniteGaussianLaplaceKernel sigma tau)
      (pairedEtaLogMeasure.prod pairedEtaLogMeasure) := by
  have hsigmaInt :=
    integrable_rexp_neg_mul_pairedEtaLogMeasure hsigma
  have hmajor := hsigmaInt.mul_prod hsigmaInt
  apply hmajor.mono
  · exact (show Continuous
      (pairedEtaFiniteGaussianLaplaceKernel sigma tau) by
        unfold pairedEtaFiniteGaussianLaplaceKernel
        fun_prop).aestronglyMeasurable
  · exact Eventually.of_forall fun p => by
      unfold pairedEtaFiniteGaussianLaplaceKernel
      simp only [Real.norm_eq_abs,
        abs_of_pos (mul_pos (Real.exp_pos _) (Real.exp_pos _))]
      have hquad : -(p.1 - p.2) ^ 2 / (4 * tau) ≤ 0 := by
        exact div_nonpos_of_nonpos_of_nonneg
          (neg_nonpos.mpr (sq_nonneg _)) (by positivity)
      have hdamp : Real.exp (-(p.1 - p.2) ^ 2 / (4 * tau)) ≤ 1 := by
        simpa only [Real.exp_zero] using Real.exp_le_exp.mpr hquad
      rw [show Real.exp (-sigma * (p.1 + p.2)) =
          Real.exp (-sigma * p.1) * Real.exp (-sigma * p.2) by
        rw [← Real.exp_add]
        congr 1
        ring]
      exact mul_le_of_le_one_right
        (mul_nonneg (Real.exp_pos _).le (Real.exp_pos _).le) hdamp

/-- Expanded iterated-integral form of the exact infinite positive eta Gram
identity. -/
theorem pairedEtaGaussianLaplaceNorm_eq_doubleIntegral
    {sigma tau : ℝ} (hsigma : 0 < sigma) (htau : 0 < tau) :
    pairedEtaGaussianLaplaceNorm sigma tau =
      Real.sqrt (Real.pi / tau) *
        ∫ t : ℝ, ∫ u : ℝ,
          pairedEtaFiniteGaussianLaplaceKernel sigma tau (t, u)
          ∂pairedEtaLogMeasure
          ∂pairedEtaLogMeasure := by
  rw [pairedEtaGaussianLaplaceNorm_eq_gram hsigma htau]
  unfold pairedEtaGaussianLaplaceGram
  rw [integral_prod _
    (integrable_pairedEtaGaussianLaplaceKernel hsigma htau)]

/-- The infinite eta Gaussian Gram form is nonnegative. -/
theorem pairedEtaGaussianLaplaceGram_nonneg (sigma tau : ℝ) :
    0 ≤ pairedEtaGaussianLaplaceGram sigma tau := by
  unfold pairedEtaGaussianLaplaceGram
  apply mul_nonneg (Real.sqrt_nonneg _)
  apply integral_nonneg
  intro p
  unfold pairedEtaFiniteGaussianLaplaceKernel
  positivity

/-- Consequently, the raw infinite eta Gaussian norm is nonnegative at every
positive horizontal tilt and Gaussian time. -/
theorem pairedEtaGaussianLaplaceNorm_nonneg
    {sigma tau : ℝ} (hsigma : 0 < sigma) (htau : 0 < tau) :
    0 ≤ pairedEtaGaussianLaplaceNorm sigma tau := by
  rw [pairedEtaGaussianLaplaceNorm_eq_gram hsigma htau]
  exact pairedEtaGaussianLaplaceGram_nonneg sigma tau

/-- Inside the open critical strip, the raw positive-Laplace energy is the
completed symmetric energy divided by its strictly positive completion
weight. -/
theorem normSq_pairedEtaLaplacePartition_eq_completedEnergy_div_weight
    {s : ℂ} (hspos : 0 < s.re) (hslt : s.re < 1) :
    Complex.normSq (pairedEtaLaplacePartition s) =
      pairedEtaCompletedLaplaceEnergy s /
        pairedEtaCompletedLaplaceWeight s := by
  unfold pairedEtaCompletedLaplaceEnergy
  rw [mul_div_cancel_left₀ _
    (pairedEtaCompletedLaplaceWeight_pos hspos hslt).ne']

/-- The raw infinite Gaussian Gram is the Gaussian integral of the completed
energy divided by the local completion weight. -/
theorem pairedEtaGaussianLaplaceNorm_eq_completedEnergy_div_weight
    {sigma : ℝ} (hsigma : 0 < sigma) (hsigmaOne : sigma < 1)
    (tau : ℝ) :
    pairedEtaGaussianLaplaceNorm sigma tau =
      ∫ y : ℝ, translatedGaussian tau 0 y *
        (pairedEtaCompletedLaplaceEnergy
            ((sigma : ℂ) + (y : ℂ) * Complex.I) /
          pairedEtaCompletedLaplaceWeight
            ((sigma : ℂ) + (y : ℂ) * Complex.I)) := by
  unfold pairedEtaGaussianLaplaceNorm
  apply integral_congr_ae
  exact Eventually.of_forall fun y => by
    change translatedGaussian tau 0 y *
        Complex.normSq (pairedEtaLaplacePartition
          ((sigma : ℂ) + (y : ℂ) * Complex.I)) =
      translatedGaussian tau 0 y *
        (pairedEtaCompletedLaplaceEnergy
            ((sigma : ℂ) + (y : ℂ) * Complex.I) /
          pairedEtaCompletedLaplaceWeight
            ((sigma : ℂ) + (y : ℂ) * Complex.I))
    rw [normSq_pairedEtaLaplacePartition_eq_completedEnergy_div_weight
      (by simpa using hsigma) (by simpa using hsigmaOne)]

/-- After reflecting the horizontal tilt, the same symmetric completed
energy is divided by the complementary completion weight. -/
theorem
    pairedEtaGaussianLaplaceNorm_complementary_eq_completedEnergy_div_weight
    {sigma : ℝ} (hsigma : 0 < sigma) (hsigmaOne : sigma < 1)
    (tau : ℝ) :
    pairedEtaGaussianLaplaceNorm (1 - sigma) tau =
      ∫ y : ℝ, translatedGaussian tau 0 y *
        (pairedEtaCompletedLaplaceEnergy
            ((sigma : ℂ) + (y : ℂ) * Complex.I) /
          pairedEtaCompletedLaplaceWeight
            (((1 - sigma : ℝ) : ℂ) +
              (y : ℂ) * Complex.I)) := by
  rw [pairedEtaGaussianLaplaceNorm_eq_completedEnergy_div_weight
    (sigma := 1 - sigma) (sub_pos.mpr hsigmaOne) (by linarith) tau]
  apply integral_congr_ae
  exact Eventually.of_forall fun y => by
    change translatedGaussian tau 0 y *
        (pairedEtaCompletedLaplaceEnergy
            (((1 - sigma : ℝ) : ℂ) + (y : ℂ) * Complex.I) /
          pairedEtaCompletedLaplaceWeight
            (((1 - sigma : ℝ) : ℂ) + (y : ℂ) * Complex.I)) =
      translatedGaussian tau 0 y *
        (pairedEtaCompletedLaplaceEnergy
            ((sigma : ℂ) + (y : ℂ) * Complex.I) /
          pairedEtaCompletedLaplaceWeight
            (((1 - sigma : ℝ) : ℂ) + (y : ℂ) * Complex.I))
    rw [← one_sub_conj_vertical]
    rw [pairedEtaCompletedLaplaceEnergy_one_sub_conj
      (by simpa using hsigma) (by simpa using hsigmaOne)
      ]

/-- The completed-energy-over-weight Gaussian integrand is genuinely
integrable. -/
theorem integrable_pairedEtaCompletedEnergy_div_weight
    {sigma tau : ℝ} (hsigma : 0 < sigma) (hsigmaOne : sigma < 1)
    (htau : 0 < tau) :
    Integrable (fun y : ℝ ↦ translatedGaussian tau 0 y *
      (pairedEtaCompletedLaplaceEnergy
          ((sigma : ℂ) + (y : ℂ) * Complex.I) /
        pairedEtaCompletedLaplaceWeight
          ((sigma : ℂ) + (y : ℂ) * Complex.I))) := by
  apply (integrable_pairedEtaGaussianLaplaceNorm hsigma htau).congr
  exact Eventually.of_forall fun y => by
    change translatedGaussian tau 0 y *
        Complex.normSq (pairedEtaLaplacePartition
          ((sigma : ℂ) + (y : ℂ) * Complex.I)) =
      translatedGaussian tau 0 y *
        (pairedEtaCompletedLaplaceEnergy
            ((sigma : ℂ) + (y : ℂ) * Complex.I) /
          pairedEtaCompletedLaplaceWeight
            ((sigma : ℂ) + (y : ℂ) * Complex.I))
    rw [normSq_pairedEtaLaplacePartition_eq_completedEnergy_div_weight
      (by simpa using hsigma) (by simpa using hsigmaOne)]

/-- The same symmetric completed energy divided by the complementary weight
is genuinely Gaussian-integrable. -/
theorem integrable_pairedEtaCompletedEnergy_div_complementaryWeight
    {sigma tau : ℝ} (hsigma : 0 < sigma) (hsigmaOne : sigma < 1)
    (htau : 0 < tau) :
    Integrable (fun y : ℝ ↦ translatedGaussian tau 0 y *
      (pairedEtaCompletedLaplaceEnergy
          ((sigma : ℂ) + (y : ℂ) * Complex.I) /
        pairedEtaCompletedLaplaceWeight
          (((1 - sigma : ℝ) : ℂ) +
            (y : ℂ) * Complex.I))) := by
  have hraw := integrable_pairedEtaGaussianLaplaceNorm
    (sub_pos.mpr hsigmaOne) htau
  apply hraw.congr
  exact Eventually.of_forall fun y => by
    change translatedGaussian tau 0 y *
        Complex.normSq (pairedEtaLaplacePartition
          (((1 - sigma : ℝ) : ℂ) + (y : ℂ) * Complex.I)) =
      translatedGaussian tau 0 y *
        (pairedEtaCompletedLaplaceEnergy
            ((sigma : ℂ) + (y : ℂ) * Complex.I) /
          pairedEtaCompletedLaplaceWeight
            (((1 - sigma : ℝ) : ℂ) + (y : ℂ) * Complex.I))
    rw [normSq_pairedEtaLaplacePartition_eq_completedEnergy_div_weight
      (by simpa using sub_pos.mpr hsigmaOne)
      (by norm_num; linarith)]
    rw [← one_sub_conj_vertical]
    rw [pairedEtaCompletedLaplaceEnergy_one_sub_conj
      (by simpa using hsigma) (by simpa using hsigmaOne)
      ]

/-- The entire asymmetry of the two raw complementary infinite eta Gaussian
Grams is exactly the reciprocal-completion-weight distortion integrated
against their common completed energy. -/
theorem
    pairedEtaGaussianLaplaceNorm_sub_complementary_eq_completionWeightDistortion
    {sigma tau : ℝ} (hsigma : 0 < sigma) (hsigmaOne : sigma < 1)
    (htau : 0 < tau) :
    pairedEtaGaussianLaplaceNorm sigma tau -
        pairedEtaGaussianLaplaceNorm (1 - sigma) tau =
      ∫ y : ℝ, translatedGaussian tau 0 y *
        pairedEtaCompletedLaplaceEnergy
            ((sigma : ℂ) + (y : ℂ) * Complex.I) *
          ((pairedEtaCompletedLaplaceWeight
              ((sigma : ℂ) + (y : ℂ) * Complex.I))⁻¹ -
            (pairedEtaCompletedLaplaceWeight
              (((1 - sigma : ℝ) : ℂ) +
                (y : ℂ) * Complex.I))⁻¹) := by
  rw [pairedEtaGaussianLaplaceNorm_eq_completedEnergy_div_weight
      hsigma hsigmaOne tau,
    pairedEtaGaussianLaplaceNorm_complementary_eq_completedEnergy_div_weight
      hsigma hsigmaOne tau,
    ← integral_sub
      (integrable_pairedEtaCompletedEnergy_div_weight
        hsigma hsigmaOne htau)
      (integrable_pairedEtaCompletedEnergy_div_complementaryWeight
        hsigma hsigmaOne htau)]
  apply integral_congr_ae
  exact Eventually.of_forall fun y => by
    change translatedGaussian tau 0 y *
          (pairedEtaCompletedLaplaceEnergy
              ((sigma : ℂ) + (y : ℂ) * Complex.I) /
            pairedEtaCompletedLaplaceWeight
              ((sigma : ℂ) + (y : ℂ) * Complex.I)) -
        translatedGaussian tau 0 y *
          (pairedEtaCompletedLaplaceEnergy
              ((sigma : ℂ) + (y : ℂ) * Complex.I) /
            pairedEtaCompletedLaplaceWeight
              (((1 - sigma : ℝ) : ℂ) +
                (y : ℂ) * Complex.I)) =
      translatedGaussian tau 0 y *
        pairedEtaCompletedLaplaceEnergy
            ((sigma : ℂ) + (y : ℂ) * Complex.I) *
          ((pairedEtaCompletedLaplaceWeight
              ((sigma : ℂ) + (y : ℂ) * Complex.I))⁻¹ -
            (pairedEtaCompletedLaplaceWeight
              (((1 - sigma : ℝ) : ℂ) +
                (y : ℂ) * Complex.I))⁻¹)
    rw [div_eq_mul_inv, div_eq_mul_inv]
    ring

end


end RiemannGaussian
