import RiemannGaussian.RiemannXiSuzukiPositiveCriticalStripEtaFiniteGaussianGram
import RiemannGaussian.RiemannXiSuzukiPositiveCriticalStripEtaFiniteLaplacePartition

/-!
# The finite paired-eta positive Gaussian--Laplace Gram identity

This module realizes the finite positive Laplace partition underlying paired
eta as a finite positive measure. Its Gaussian vertical-line norm is then
identified, by a proved Fubini exchange and the Gaussian Fourier transform,
with a positive kernel integral over two copies of that measure.
-/

open Complex Filter MeasureTheory Metric Set Topology
open scoped Classical ComplexConjugate ENNReal Interval Topology

namespace RiemannGaussian

noncomputable section

/-- The finite positive logarithmic-time measure underlying the first `N`
paired eta intervals. -/
def pairedEtaFiniteLogMeasure (N : ℕ) : Measure ℝ :=
  ∑ n ∈ Finset.range N,
    volume.restrict
      (Ioc (Real.log (2 * n + 1)) (Real.log (2 * n + 2)))

/-- The finite logarithmic eta measure is sigma-finite. -/
instance pairedEtaFiniteLogMeasure.instSFinite (N : ℕ) :
    SFinite (pairedEtaFiniteLogMeasure N) := by
  unfold pairedEtaFiniteLogMeasure
  infer_instance

/-- Every complex exponential is integrable against the finite logarithmic
eta measure. -/
theorem integrable_cexp_neg_mul_pairedEtaFiniteLogMeasure
    (N : ℕ) (s : ℂ) :
    Integrable (fun t : ℝ => Complex.exp (-s * t))
      (pairedEtaFiniteLogMeasure N) := by
  unfold pairedEtaFiniteLogMeasure
  rw [integrable_finsetSum_measure]
  intro n hn
  change IntegrableOn (fun t : ℝ => Complex.exp (-s * t))
    (Ioc (Real.log (2 * n + 1)) (Real.log (2 * n + 2)))
  apply IntegrableOn.mono_set
    ((show Continuous (fun t : ℝ => Complex.exp (-s * t)) by
      fun_prop).continuousOn.integrableOn_Icc)
  exact Ioc_subset_Icc_self

/-- Every real exponential tilt is integrable against the finite logarithmic
eta measure. -/
theorem integrable_rexp_neg_mul_pairedEtaFiniteLogMeasure
    (N : ℕ) (sigma : ℝ) :
    Integrable (fun t : ℝ => Real.exp (-sigma * t))
      (pairedEtaFiniteLogMeasure N) := by
  unfold pairedEtaFiniteLogMeasure
  rw [integrable_finsetSum_measure]
  intro n hn
  change IntegrableOn (fun t : ℝ => Real.exp (-sigma * t))
    (Ioc (Real.log (2 * n + 1)) (Real.log (2 * n + 2)))
  apply IntegrableOn.mono_set
    ((show Continuous (fun t : ℝ => Real.exp (-sigma * t)) by
      fun_prop).continuousOn.integrableOn_Icc)
  exact Ioc_subset_Icc_self

/-- The existing finite eta Laplace partition is literally the transform of
the finite positive logarithmic-time measure. -/
theorem pairedEtaFiniteLaplacePartition_eq_integral_logMeasure
    (N : ℕ) (s : ℂ) :
    pairedEtaFiniteLaplacePartition N s =
      ∫ t : ℝ, Complex.exp (-s * t) ∂pairedEtaFiniteLogMeasure N := by
  unfold pairedEtaFiniteLaplacePartition pairedEtaFiniteLogMeasure
  rw [integral_finsetSum_measure]
  · apply Finset.sum_congr rfl
    intro n hn
    rw [← intervalIntegral.integral_of_le
      (pairedEtaFiniteLogInterval_pos n).le]
  · intro n hn
    change IntegrableOn (fun t : ℝ => Complex.exp (-s * t))
      (Ioc (Real.log (2 * n + 1)) (Real.log (2 * n + 2)))
    apply IntegrableOn.mono_set
      ((show Continuous (fun t : ℝ => Complex.exp (-s * t)) by
        fun_prop).continuousOn.integrableOn_Icc)
    exact Ioc_subset_Icc_self

/-- Away from the origin, the positive Laplace partition is exactly the
finite paired-eta polynomial divided by its complex argument. -/
theorem pairedEtaFiniteLaplacePartition_eq_partialSum_div
    (N : ℕ) {s : ℂ} (hs : s ≠ 0) :
    pairedEtaFiniteLaplacePartition N s =
      pairedEtaCorePartialSum N s / s := by
  apply (eq_div_iff hs).2
  rw [pairedEtaCorePartialSum_eq_mul_finiteLaplacePartition]
  ring

/-- Gaussian vertical-line norm of the finite positive Laplace partition. -/
def pairedEtaFiniteGaussianLaplaceNorm
    (N : ℕ) (sigma tau : ℝ) : ℝ :=
  ∫ y : ℝ, translatedGaussian tau 0 y *
    Complex.normSq (pairedEtaFiniteLaplacePartition N
      ((sigma : ℂ) + (y : ℂ) * Complex.I))

/-- The positive two-time kernel generated by the Gaussian Fourier
transform. -/
def pairedEtaFiniteGaussianLaplaceKernel
    (sigma tau : ℝ) (p : ℝ × ℝ) : ℝ :=
  Real.exp (-sigma * (p.1 + p.2)) *
    Real.exp (-(p.1 - p.2) ^ 2 / (4 * tau))

/-- The positive double-measure Gram form predicted by the Gaussian transform
of the finite eta Laplace partition. -/
def pairedEtaFiniteGaussianLaplaceGram
    (N : ℕ) (sigma tau : ℝ) : ℝ :=
  Real.sqrt (Real.pi / tau) *
    ∫ p : ℝ × ℝ, pairedEtaFiniteGaussianLaplaceKernel sigma tau p
      ∂(pairedEtaFiniteLogMeasure N).prod
        (pairedEtaFiniteLogMeasure N)

private def pairedEtaFiniteGaussianLaplaceJoint
    (sigma tau : ℝ) (z : ℝ × (ℝ × ℝ)) : ℂ :=
  (Real.exp (-sigma * (z.2.1 + z.2.2)) : ℂ) *
    complexTranslatedGaussianOscillation tau 0
      (z.2.2 - z.2.1) z.1

private theorem pairedEtaFiniteGaussianLaplaceJoint_eq_laplaceProduct
    (sigma tau y t u : ℝ) :
    pairedEtaFiniteGaussianLaplaceJoint sigma tau (y, (t, u)) =
      (translatedGaussian tau 0 y : ℂ) *
        Complex.exp
          (-((sigma : ℂ) + (y : ℂ) * Complex.I) * t) *
        starRingEnd ℂ
          (Complex.exp
            (-((sigma : ℂ) + (y : ℂ) * Complex.I) * u)) := by
  unfold pairedEtaFiniteGaussianLaplaceJoint
    complexTranslatedGaussianOscillation translatedGaussian
  rw [Complex.ofReal_exp, Complex.ofReal_exp, ← Complex.exp_conj]
  simp only [map_neg, map_mul, map_add, Complex.conj_ofReal,
    Complex.conj_I, neg_mul]
  rw [← Complex.exp_add, ← Complex.exp_add, ← Complex.exp_add]
  congr 1
  push_cast
  ring

private theorem integrable_pairedEtaFiniteGaussianLaplaceJoint
    (N : ℕ) (sigma : ℝ) {tau : ℝ} (htau : 0 < tau) :
    Integrable (pairedEtaFiniteGaussianLaplaceJoint sigma tau)
      (volume.prod ((pairedEtaFiniteLogMeasure N).prod
        (pairedEtaFiniteLogMeasure N))) := by
  have hy := integrable_translatedGaussian htau 0
  have hsigma :=
    integrable_rexp_neg_mul_pairedEtaFiniteLogMeasure N sigma
  have hmajor := hy.mul_prod (hsigma.mul_prod hsigma)
  apply hmajor.mono
  · exact (show Continuous
      (pairedEtaFiniteGaussianLaplaceJoint sigma tau) by
        unfold pairedEtaFiniteGaussianLaplaceJoint
          complexTranslatedGaussianOscillation
        fun_prop).aestronglyMeasurable
  · exact Eventually.of_forall fun z => by
      apply le_of_eq
      unfold pairedEtaFiniteGaussianLaplaceJoint
        complexTranslatedGaussianOscillation translatedGaussian
      simp only [norm_mul, Complex.norm_real, Real.norm_eq_abs,
        abs_of_pos (Real.exp_pos _), Complex.norm_exp,
        Complex.add_re, Complex.ofReal_re, Complex.mul_re,
        Complex.I_re, Complex.I_im, Complex.ofReal_im,
        mul_zero, zero_mul, sub_zero]
      norm_num [Complex.mul_im]
      rw [← Real.exp_add, ← Real.exp_add, ← Real.exp_add]
      congr 1
      ring

private theorem integral_pairedEtaFiniteGaussianLaplaceJoint_prod
    (N : ℕ) (sigma tau y : ℝ) :
    (∫ p : ℝ × ℝ,
        pairedEtaFiniteGaussianLaplaceJoint sigma tau (y, p)
        ∂(pairedEtaFiniteLogMeasure N).prod
          (pairedEtaFiniteLogMeasure N)) =
      (translatedGaussian tau 0 y : ℂ) *
        pairedEtaFiniteLaplacePartition N
          ((sigma : ℂ) + (y : ℂ) * Complex.I) *
        starRingEnd ℂ
          (pairedEtaFiniteLaplacePartition N
            ((sigma : ℂ) + (y : ℂ) * Complex.I)) := by
  rw [show
    (fun p : ℝ × ℝ =>
      pairedEtaFiniteGaussianLaplaceJoint sigma tau (y, p)) =
      (fun p : ℝ × ℝ =>
        (translatedGaussian tau 0 y : ℂ) *
          (Complex.exp
              (-((sigma : ℂ) + (y : ℂ) * Complex.I) * p.1) *
            starRingEnd ℂ
              (Complex.exp
                (-((sigma : ℂ) + (y : ℂ) * Complex.I) * p.2)))) by
      funext p
      rw [pairedEtaFiniteGaussianLaplaceJoint_eq_laplaceProduct]
      ring]
  rw [integral_const_mul]
  rw [integral_prod_mul
    (μ := pairedEtaFiniteLogMeasure N)
    (ν := pairedEtaFiniteLogMeasure N)
    (fun t : ℝ => Complex.exp
      (-((sigma : ℂ) + (y : ℂ) * Complex.I) * t))
    (fun u : ℝ => starRingEnd ℂ (Complex.exp
      (-((sigma : ℂ) + (y : ℂ) * Complex.I) * u)))]
  rw [integral_conj]
  rw [← pairedEtaFiniteLaplacePartition_eq_integral_logMeasure]
  ring

private theorem integral_pairedEtaFiniteGaussianLaplaceJoint_volume
    (sigma : ℝ) {tau : ℝ} (htau : 0 < tau) (p : ℝ × ℝ) :
    (∫ y : ℝ,
        pairedEtaFiniteGaussianLaplaceJoint sigma tau (y, p)) =
      (Real.sqrt (Real.pi / tau) : ℂ) *
        (pairedEtaFiniteGaussianLaplaceKernel sigma tau p : ℂ) := by
  unfold pairedEtaFiniteGaussianLaplaceJoint
  change (∫ y : ℝ,
      (Real.exp (-sigma * (p.1 + p.2)) : ℂ) *
        complexTranslatedGaussianOscillation tau 0
          (p.2 - p.1) y) = _
  rw [integral_const_mul,
    integral_complexTranslatedGaussianOscillation htau]
  unfold pairedEtaFiniteGaussianLaplaceKernel
  norm_num
  ring_nf

/-- The Gaussian norm of the finite positive eta partition is integrable at
every positive Gaussian time. -/
theorem integrable_pairedEtaFiniteGaussianLaplaceNorm
    (N : ℕ) (sigma : ℝ) {tau : ℝ} (htau : 0 < tau) :
    Integrable (fun y : ℝ => translatedGaussian tau 0 y *
      Complex.normSq (pairedEtaFiniteLaplacePartition N
        ((sigma : ℂ) + (y : ℂ) * Complex.I))) := by
  have hjoint :=
    integrable_pairedEtaFiniteGaussianLaplaceJoint N sigma htau
  have houter := hjoint.integral_prod_left
  have hcomplex : Integrable (fun y : ℝ =>
      ((translatedGaussian tau 0 y *
        Complex.normSq (pairedEtaFiniteLaplacePartition N
          ((sigma : ℂ) + (y : ℂ) * Complex.I)) : ℝ) : ℂ)) := by
    apply houter.congr
    exact Eventually.of_forall fun y => by
      change (∫ p : ℝ × ℝ,
          pairedEtaFiniteGaussianLaplaceJoint sigma tau (y, p)
          ∂(pairedEtaFiniteLogMeasure N).prod
            (pairedEtaFiniteLogMeasure N)) =
        ((translatedGaussian tau 0 y *
          Complex.normSq (pairedEtaFiniteLaplacePartition N
            ((sigma : ℂ) + (y : ℂ) * Complex.I)) : ℝ) : ℂ)
      rw [integral_pairedEtaFiniteGaussianLaplaceJoint_prod]
      push_cast
      rw [Complex.normSq_eq_conj_mul_self]
      ring
  have hre := hcomplex.re
  rw [RCLike.re_eq_complex_re] at hre
  simpa using hre

/-- Exact positive Gaussian--Laplace Gram identity for the finite eta
partition. Both integrations on the right are against the genuine finite
positive logarithmic eta measure. -/
theorem pairedEtaFiniteGaussianLaplaceNorm_eq_gram
    (N : ℕ) (sigma : ℝ) {tau : ℝ} (htau : 0 < tau) :
    pairedEtaFiniteGaussianLaplaceNorm N sigma tau =
      pairedEtaFiniteGaussianLaplaceGram N sigma tau := by
  apply Complex.ofReal_injective
  have hjoint :=
    integrable_pairedEtaFiniteGaussianLaplaceJoint N sigma htau
  calc
    (pairedEtaFiniteGaussianLaplaceNorm N sigma tau : ℂ) =
        ∫ y : ℝ, ∫ p : ℝ × ℝ,
          pairedEtaFiniteGaussianLaplaceJoint sigma tau (y, p)
          ∂(pairedEtaFiniteLogMeasure N).prod
            (pairedEtaFiniteLogMeasure N) := by
      unfold pairedEtaFiniteGaussianLaplaceNorm
      rw [← integral_complex_ofReal]
      apply integral_congr_ae
      exact Eventually.of_forall fun y => by
        change ((translatedGaussian tau 0 y *
            Complex.normSq (pairedEtaFiniteLaplacePartition N
              ((sigma : ℂ) + (y : ℂ) * Complex.I)) : ℝ) : ℂ) =
          ∫ p : ℝ × ℝ,
            pairedEtaFiniteGaussianLaplaceJoint sigma tau (y, p)
            ∂(pairedEtaFiniteLogMeasure N).prod
              (pairedEtaFiniteLogMeasure N)
        rw [integral_pairedEtaFiniteGaussianLaplaceJoint_prod]
        push_cast
        rw [Complex.normSq_eq_conj_mul_self]
        ring
    _ = ∫ z : ℝ × (ℝ × ℝ),
          pairedEtaFiniteGaussianLaplaceJoint sigma tau z
          ∂volume.prod ((pairedEtaFiniteLogMeasure N).prod
            (pairedEtaFiniteLogMeasure N)) := by
      exact integral_integral hjoint
    _ = ∫ p : ℝ × ℝ, ∫ y : ℝ,
          pairedEtaFiniteGaussianLaplaceJoint sigma tau (y, p)
          ∂volume
          ∂(pairedEtaFiniteLogMeasure N).prod
            (pairedEtaFiniteLogMeasure N) := by
      exact integral_prod_symm _ hjoint
    _ = ∫ p : ℝ × ℝ,
          (Real.sqrt (Real.pi / tau) : ℂ) *
            (pairedEtaFiniteGaussianLaplaceKernel sigma tau p : ℂ)
          ∂(pairedEtaFiniteLogMeasure N).prod
            (pairedEtaFiniteLogMeasure N) := by
      apply integral_congr_ae
      exact Eventually.of_forall fun p =>
        integral_pairedEtaFiniteGaussianLaplaceJoint_volume
          sigma htau p
    _ = (pairedEtaFiniteGaussianLaplaceGram N sigma tau : ℂ) := by
      unfold pairedEtaFiniteGaussianLaplaceGram
      rw [integral_const_mul, integral_complex_ofReal]
      push_cast
      rfl

/-- The positive Gaussian--Laplace kernel is integrable over the finite eta
product measure at positive Gaussian time. -/
theorem integrable_pairedEtaFiniteGaussianLaplaceKernel
    (N : ℕ) (sigma : ℝ) {tau : ℝ} (htau : 0 < tau) :
    Integrable (pairedEtaFiniteGaussianLaplaceKernel sigma tau)
      ((pairedEtaFiniteLogMeasure N).prod
        (pairedEtaFiniteLogMeasure N)) := by
  have hsigma :=
    integrable_rexp_neg_mul_pairedEtaFiniteLogMeasure N sigma
  have hmajor := hsigma.mul_prod hsigma
  apply hmajor.mono
  · exact (show Continuous
      (pairedEtaFiniteGaussianLaplaceKernel sigma tau) by
        unfold pairedEtaFiniteGaussianLaplaceKernel
        fun_prop).aestronglyMeasurable
  · exact Eventually.of_forall fun p => by
      unfold pairedEtaFiniteGaussianLaplaceKernel
      simp only [Real.norm_eq_abs,
        abs_of_pos (mul_pos (Real.exp_pos _) (Real.exp_pos _))]
      have hquad : -(p.1 - p.2) ^ 2 / (4 * tau) ≤ 0 := by
        exact div_nonpos_of_nonpos_of_nonneg
          (neg_nonpos.mpr (sq_nonneg _)) (by positivity)
      have hdamp : Real.exp (-(p.1 - p.2) ^ 2 / (4 * tau)) ≤ 1 := by
        simpa only [Real.exp_zero] using Real.exp_le_exp.mpr hquad
      rw [show Real.exp (-sigma * (p.1 + p.2)) =
          Real.exp (-sigma * p.1) * Real.exp (-sigma * p.2) by
        rw [← Real.exp_add]
        congr 1
        ring]
      exact mul_le_of_le_one_right
        (mul_nonneg (Real.exp_pos _).le (Real.exp_pos _).le) hdamp

/-- Expanded Fubini form of the exact finite eta positive Gram identity. -/
theorem pairedEtaFiniteGaussianLaplaceNorm_eq_doubleIntegral
    (N : ℕ) (sigma : ℝ) {tau : ℝ} (htau : 0 < tau) :
    pairedEtaFiniteGaussianLaplaceNorm N sigma tau =
      Real.sqrt (Real.pi / tau) *
        ∫ t : ℝ, ∫ u : ℝ,
          pairedEtaFiniteGaussianLaplaceKernel sigma tau (t, u)
          ∂pairedEtaFiniteLogMeasure N
          ∂pairedEtaFiniteLogMeasure N := by
  rw [pairedEtaFiniteGaussianLaplaceNorm_eq_gram N sigma htau]
  unfold pairedEtaFiniteGaussianLaplaceGram
  rw [integral_prod _
    (integrable_pairedEtaFiniteGaussianLaplaceKernel N sigma htau)]

/-- On a nonzero vertical line, the Laplace Gaussian norm is literally the
Gaussian norm of the normalized finite eta polynomial `E_N(s) / s`. -/
theorem pairedEtaFiniteGaussianLaplaceNorm_eq_normalizedPartialSum
    (N : ℕ) {sigma : ℝ} (hsigma : sigma ≠ 0) (tau : ℝ) :
    pairedEtaFiniteGaussianLaplaceNorm N sigma tau =
      ∫ y : ℝ, translatedGaussian tau 0 y *
        Complex.normSq
          (pairedEtaCorePartialSum N
            ((sigma : ℂ) + (y : ℂ) * Complex.I) /
              ((sigma : ℂ) + (y : ℂ) * Complex.I)) := by
  unfold pairedEtaFiniteGaussianLaplaceNorm
  apply integral_congr_ae
  exact Eventually.of_forall fun y => by
    have hs : (sigma : ℂ) + (y : ℂ) * Complex.I ≠ 0 := by
      intro hzero
      have hre := congrArg Complex.re hzero
      norm_num [Complex.mul_re] at hre
      exact hsigma hre
    change translatedGaussian tau 0 y *
        Complex.normSq (pairedEtaFiniteLaplacePartition N
          ((sigma : ℂ) + (y : ℂ) * Complex.I)) =
      translatedGaussian tau 0 y *
        Complex.normSq
          (pairedEtaCorePartialSum N
            ((sigma : ℂ) + (y : ℂ) * Complex.I) /
              ((sigma : ℂ) + (y : ℂ) * Complex.I))
    rw [pairedEtaFiniteLaplacePartition_eq_partialSum_div N hs]

/-- Thus the normalized finite eta Gaussian norm has the exact positive
double-integral representation over the eta logarithmic support. -/
theorem normalizedPairedEtaFiniteGaussianNorm_eq_doubleIntegral
    (N : ℕ) {sigma : ℝ} (hsigma : sigma ≠ 0)
    {tau : ℝ} (htau : 0 < tau) :
    (∫ y : ℝ, translatedGaussian tau 0 y *
        Complex.normSq
          (pairedEtaCorePartialSum N
            ((sigma : ℂ) + (y : ℂ) * Complex.I) /
              ((sigma : ℂ) + (y : ℂ) * Complex.I))) =
      Real.sqrt (Real.pi / tau) *
        ∫ t : ℝ, ∫ u : ℝ,
          pairedEtaFiniteGaussianLaplaceKernel sigma tau (t, u)
          ∂pairedEtaFiniteLogMeasure N
          ∂pairedEtaFiniteLogMeasure N := by
  rw [← pairedEtaFiniteGaussianLaplaceNorm_eq_normalizedPartialSum
      N hsigma tau,
    pairedEtaFiniteGaussianLaplaceNorm_eq_doubleIntegral N sigma htau]

/-- The finite eta Gaussian--Laplace kernel is pointwise strictly positive. -/
theorem pairedEtaFiniteGaussianLaplaceKernel_pos
    (sigma tau : ℝ) (p : ℝ × ℝ) :
    0 < pairedEtaFiniteGaussianLaplaceKernel sigma tau p := by
  unfold pairedEtaFiniteGaussianLaplaceKernel
  exact mul_pos (Real.exp_pos _) (Real.exp_pos _)

/-- The finite positive-measure Gaussian--Laplace Gram form is nonnegative. -/
theorem pairedEtaFiniteGaussianLaplaceGram_nonneg
    (N : ℕ) (sigma tau : ℝ) :
    0 ≤ pairedEtaFiniteGaussianLaplaceGram N sigma tau := by
  unfold pairedEtaFiniteGaussianLaplaceGram
  apply mul_nonneg (Real.sqrt_nonneg _)
  apply integral_nonneg
  exact fun p => (pairedEtaFiniteGaussianLaplaceKernel_pos sigma tau p).le

/-- The original Gaussian norm of the finite positive eta partition is
nonnegative. -/
theorem pairedEtaFiniteGaussianLaplaceNorm_nonneg
    (N : ℕ) (sigma tau : ℝ) :
    0 ≤ pairedEtaFiniteGaussianLaplaceNorm N sigma tau := by
  unfold pairedEtaFiniteGaussianLaplaceNorm
  apply integral_nonneg
  intro y
  exact mul_nonneg (by
    unfold translatedGaussian
    positivity) (Complex.normSq_nonneg _)

private theorem integrable_pairedEtaFiniteGaussianLaplaceKernel_right
    (N : ℕ) (sigma tau t : ℝ) :
    Integrable
      (fun u : ℝ =>
        pairedEtaFiniteGaussianLaplaceKernel sigma tau (t, u))
      (pairedEtaFiniteLogMeasure N) := by
  unfold pairedEtaFiniteLogMeasure
  rw [integrable_finsetSum_measure]
  intro n hn
  change IntegrableOn
    (fun u : ℝ =>
      pairedEtaFiniteGaussianLaplaceKernel sigma tau (t, u))
    (Ioc (Real.log (2 * n + 1)) (Real.log (2 * n + 2)))
  apply IntegrableOn.mono_set
    ((show Continuous (fun u : ℝ =>
        pairedEtaFiniteGaussianLaplaceKernel sigma tau (t, u)) by
      unfold pairedEtaFiniteGaussianLaplaceKernel
      fun_prop).continuousOn.integrableOn_Icc)
  exact Ioc_subset_Icc_self

private theorem integral_pairedEtaFiniteGaussianLaplaceKernel_logMeasure
    (N : ℕ) (sigma tau t : ℝ) :
    (∫ u : ℝ,
        pairedEtaFiniteGaussianLaplaceKernel sigma tau (t, u)
        ∂pairedEtaFiniteLogMeasure N) =
      ∑ m ∈ Finset.range N,
        ∫ u : ℝ in
          Real.log (2 * m + 1)..Real.log (2 * m + 2),
          pairedEtaFiniteGaussianLaplaceKernel sigma tau (t, u) := by
  unfold pairedEtaFiniteLogMeasure
  rw [integral_finsetSum_measure]
  · apply Finset.sum_congr rfl
    intro m hm
    rw [← intervalIntegral.integral_of_le
      (pairedEtaFiniteLogInterval_pos m).le]
  · intro m hm
    change IntegrableOn
      (fun u : ℝ =>
        pairedEtaFiniteGaussianLaplaceKernel sigma tau (t, u))
      (Ioc (Real.log (2 * m + 1)) (Real.log (2 * m + 2)))
    apply IntegrableOn.mono_set
      ((show Continuous (fun u : ℝ =>
          pairedEtaFiniteGaussianLaplaceKernel sigma tau (t, u)) by
        unfold pairedEtaFiniteGaussianLaplaceKernel
        fun_prop).continuousOn.integrableOn_Icc)
    exact Ioc_subset_Icc_self

/-- Fully expanded finite interval form of the positive eta
Gaussian--Laplace Gram integral. -/
def pairedEtaFiniteGaussianLaplaceIntervalGram
    (N : ℕ) (sigma tau : ℝ) : ℝ :=
  Real.sqrt (Real.pi / tau) *
    ∑ n ∈ Finset.range N,
      ∫ t : ℝ in
        Real.log (2 * n + 1)..Real.log (2 * n + 2),
        ∑ m ∈ Finset.range N,
          ∫ u : ℝ in
            Real.log (2 * m + 1)..Real.log (2 * m + 2),
            pairedEtaFiniteGaussianLaplaceKernel sigma tau (t, u)

/-- The positive product-measure Gram form is exactly the explicit finite
sum of double integrals over all pairs of eta support intervals. -/
theorem pairedEtaFiniteGaussianLaplaceGram_eq_intervalGram
    (N : ℕ) (sigma : ℝ) {tau : ℝ} (htau : 0 < tau) :
    pairedEtaFiniteGaussianLaplaceGram N sigma tau =
      pairedEtaFiniteGaussianLaplaceIntervalGram N sigma tau := by
  unfold pairedEtaFiniteGaussianLaplaceGram
    pairedEtaFiniteGaussianLaplaceIntervalGram
  congr 1
  have hkernel :=
    integrable_pairedEtaFiniteGaussianLaplaceKernel N sigma htau
  rw [integral_prod _ hkernel]
  have houter := hkernel.integral_prod_left
  unfold pairedEtaFiniteLogMeasure at houter ⊢
  rw [integral_finsetSum_measure]
  · apply Finset.sum_congr rfl
    intro n hn
    rw [← intervalIntegral.integral_of_le
      (pairedEtaFiniteLogInterval_pos n).le]
    apply intervalIntegral.integral_congr
    intro t ht
    exact integral_pairedEtaFiniteGaussianLaplaceKernel_logMeasure
      N sigma tau t
  · exact integrable_finsetSum_measure.mp houter

/-- Combining the Gaussian transform with the finite support decomposition
gives a completely explicit positive double-interval identity. -/
theorem pairedEtaFiniteGaussianLaplaceNorm_eq_intervalGram
    (N : ℕ) (sigma : ℝ) {tau : ℝ} (htau : 0 < tau) :
    pairedEtaFiniteGaussianLaplaceNorm N sigma tau =
      pairedEtaFiniteGaussianLaplaceIntervalGram N sigma tau := by
  rw [pairedEtaFiniteGaussianLaplaceNorm_eq_gram N sigma htau,
    pairedEtaFiniteGaussianLaplaceGram_eq_intervalGram N sigma htau]

/-- The fully expanded finite interval Gram form is nonnegative at positive
Gaussian time. -/
theorem pairedEtaFiniteGaussianLaplaceIntervalGram_nonneg
    (N : ℕ) (sigma : ℝ) {tau : ℝ} (htau : 0 < tau) :
    0 ≤ pairedEtaFiniteGaussianLaplaceIntervalGram N sigma tau := by
  rw [← pairedEtaFiniteGaussianLaplaceGram_eq_intervalGram N sigma htau]
  exact pairedEtaFiniteGaussianLaplaceGram_nonneg N sigma tau

end

end RiemannGaussian
