/-
Copyright (c) 2026 David Sanftenberg. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Sanftenberg
-/
import RiemannGaussian.SemiprimeReflectedCompanions
import Mathlib.Data.List.Find
import RiemannGaussian.SemiprimeBitDivision

/-!
# Public proper-product sieve for the row modulus

Retain a factor witness for every composite event in a bounded public
window. Sorted events expose the first missing candidate by a linear
merge. Mathematical event/scan counts do not supply an unpriced sort or
an implicit complete bit-machine refinement.
-/

namespace RiemannGaussian.SemiprimePrimeSieve

open SemiprimeEuclidRowBudget

/-- Every proper positive product up to X, retaining both public factors.
The constructor enumerates only its actual quotient-length inner rows. -/
def properPairs (X : ℕ) : List (ℕ×ℕ) :=
  (List.range (X-1)).flatMap fun i =>
    (List.range (X/(i+2)-1)).map fun k => (i+2,k+2)

/-- The literal quotient enumeration includes every proper product and
does not construct the X by X pair rectangle. -/
theorem properPairs_mem_iff {X : ℕ} {v : ℕ×ℕ} :
    v∈properPairs X ↔ 2≤v.1 ∧ 2≤v.2 ∧ v.1*v.2≤X := by
  constructor
  · intro hv
    obtain ⟨i,hi,hv⟩ := List.mem_flatMap.mp hv
    obtain ⟨k,hk,rfl⟩ := List.mem_map.mp hv
    have hk' := List.mem_range.mp hk
    have hbound : k+2≤X/(i+2) := by omega
    refine ⟨by omega,by omega,?_⟩
    simpa only [mul_comm] using (Nat.le_div_iff_mul_le (by omega : 0 < i + 2)).mp hbound
  · rintro ⟨hd,hk,hprod⟩
    have hdX : v.1≤X := (Nat.le_mul_of_pos_right _ (by omega : 0<v.2)).trans hprod
    have hi : v.1-2<X-1 := by omega
    have hkdiv : v.2≤X/v.1 := (Nat.le_div_iff_mul_le (by omega : 0<v.1)).mpr
      (by simpa only [mul_comm] using hprod)
    have hk' : v.2-2<X/v.1-1 := by omega
    apply List.mem_flatMap.mpr
    refine ⟨v.1-2,List.mem_range.mpr hi,?_⟩
    apply List.mem_map.mpr
    refine ⟨v.2-2,?_,?_⟩
    · simpa only [Nat.sub_add_cancel hd] using List.mem_range.mpr hk'
    · ext <;> simp only [Nat.sub_add_cancel hd,Nat.sub_add_cancel hk]

/-- Both factor labels prevent event multiplicity from disappearing
before composite products are deliberately projected. -/
theorem properPairs_nodup (X : ℕ) : (properPairs X).Nodup := by
  apply List.nodup_flatMap.mpr
  constructor
  · intro i _
    apply List.nodup_range.map
    intro a b he
    have h := congrArg Prod.snd he
    change a+2=b+2 at h
    omega
  · apply List.nodup_range.imp
    intro i j hij v hi hj
    obtain ⟨a,_,ha⟩ := List.mem_map.mp hi
    obtain ⟨b,_,hb⟩ := List.mem_map.mp hj
    have he := congrArg Prod.fst (ha.trans hb.symm)
    change i+2=j+2 at he
    exact hij (by omega)

/-- Actual public event tags inject into the proved positive-product
envelope; the mathematical envelope is not generated by this sieve. -/
theorem properPairs_length_le (X : ℕ) :
    (properPairs X).length≤X*(Nat.log2 X+1)^2 := by
  have hi : Function.Injective (fun v : ℕ×ℕ => (v.1,v.2,1)) := by
    intro a b he
    exact Prod.ext (congrArg (fun v : ℕ×ℕ×ℕ => v.1) he)
      (congrArg (fun v : ℕ×ℕ×ℕ => v.2.1) he)
  have hsub : ((properPairs X).toFinset.image fun v => (v.1,v.2,1))⊆positiveTriples X := by
    intro tag ht
    obtain ⟨v,hv,rfl⟩ := Finset.mem_image.mp ht
    obtain ⟨hd,hk,hprod⟩ := properPairs_mem_iff.mp (List.mem_toFinset.mp hv)
    have hdX := (Nat.le_mul_of_pos_right _ (by omega : 0<v.2)).trans hprod
    have hkX := (Nat.le_mul_of_pos_left _ (by omega : 0<v.1)).trans hprod
    apply positiveTriples_mem_iff.mpr
    change 0<v.1 ∧ v.1≤X ∧ 0<v.2 ∧ v.2≤X ∧ 0<1 ∧ 1≤X ∧ v.1*v.2*1≤X
    exact ⟨by omega,hdX,by omega,hkX,Nat.one_pos,by omega,by simpa only [mul_one] using hprod⟩
  calc
    _ = (properPairs X).toFinset.card := (List.toFinset_card_of_nodup (properPairs_nodup X)).symm
    _ = ((properPairs X).toFinset.image fun v => (v.1,v.2,1)).card :=
      (Finset.card_image_of_injective _ hi).symm
    _ ≤ (positiveTriples X).card := Finset.card_le_card hsub
    _ ≤ _ := positiveTriples_card_le X

/-- Every event carries its two factors before the value projection. -/
def eventValues (X : ℕ) : List ℕ := (properPairs X).map fun v => v.1*v.2

/-- A public candidate in the window is marked exactly when composite;
no candidate primality test is called by the event constructor. -/
theorem eventValues_mem_iff {X n : ℕ} (hn : 2≤n) :
    n∈eventValues X ↔ n≤X ∧ ¬n.Prime := by
  constructor
  · intro hm
    obtain ⟨v,hv,he⟩ := List.mem_map.mp hm
    obtain ⟨hd,hk,hprod⟩ := properPairs_mem_iff.mp hv
    exact ⟨he ▸ hprod,(Nat.not_prime_iff_exists_mul_eq hn).mpr
      ⟨v.1,v.2,by nlinarith,by nlinarith,he⟩⟩
  · rintro ⟨hX,hcomp⟩
    obtain ⟨d,k,hd,hk,he⟩ := (Nat.not_prime_iff_exists_mul_eq hn).mp hcomp
    have hd2 : 2≤d := by
      by_contra h
      have : d≤1 := by omega
      nlinarith
    have hk2 : 2≤k := by
      by_contra h
      have : k≤1 := by omega
      nlinarith
    apply List.mem_map.mpr
    exact ⟨(d,k),properPairs_mem_iff.mpr ⟨hd2,hk2,he ▸ hX⟩,he⟩

/-- Sorted witnesses retain both factors and their full multiplicity. -/
def sortedEvents (X : ℕ) : List (ℕ×ℕ) :=
  (properPairs X).mergeSort fun v w => decide (v.1*v.2≤w.1*w.2)

/-- The downstream sorted scalar view keeps every marked event. -/
def sortedValues (X : ℕ) : List ℕ := (sortedEvents X).map fun v => v.1*v.2

theorem sortedValues_perm (X : ℕ) : (sortedValues X).Perm (eventValues X) :=
  (List.mergeSort_perm (properPairs X) _).map _

theorem sortedValues_length_le (X : ℕ) :
    (sortedValues X).length≤X*(Nat.log2 X+1)^2 := by
  rw [(sortedValues_perm X).length_eq]
  simpa only [eventValues,List.length_map] using properPairs_length_le X

theorem sortedValues_ordered (X : ℕ) : (sortedValues X).Pairwise (·≤·) := by
  have h := List.pairwise_mergeSort (le:=fun v w : ℕ×ℕ => decide (v.1*v.2≤w.1*w.2))
    (fun _ _ _ h1 h2 => by simp only [decide_eq_true_eq] at h1 h2 ⊢; exact h1.trans h2)
    (fun _ _ => by simp only [Bool.or_eq_true,decide_eq_true_eq]; exact le_total _ _) (properPairs X)
  simpa only [sortedValues,sortedEvents,List.pairwise_map,decide_eq_true_eq] using h

/-- The actual sorted merge exposes a missing candidate without scanning
the full event list independently for each primality decision. -/
def firstGap : (candidate count : ℕ) → List ℕ → Option ℕ
  | _,0,_ => none
  | candidate,_+1,[] => some candidate
  | candidate,count+1,y::ys =>
    if y<candidate then firstGap candidate (count+1) ys
    else if y=candidate then firstGap (candidate+1) count ys else some candidate
termination_by _ count products => count+products.length
decreasing_by all_goals simp_wf <;> omega

/-- A downstream complete specification, not the merge implementation. -/
def gapSpec (candidate count : ℕ) (products : List ℕ) : Option ℕ :=
  (List.range' candidate count).find? fun x => decide (x∉products)

private theorem gapSpec_skip_below {candidate count y : ℕ} {ys : List ℕ}
    (hy : y<candidate) : gapSpec candidate count (y::ys)=gapSpec candidate count ys := by
  apply List.find?_congr
  intro x hx
  obtain ⟨i,_,he⟩ := List.mem_range'.mp hx
  have hne : x≠y := by omega
  simp only [List.mem_cons,hne,false_or]

/-- The retained event order proves that the linear merge and complete
candidate specification have exactly the same first missing value. -/
theorem firstGap_eq_gapSpec (candidate count : ℕ) (products : List ℕ)
    (hordered : products.Pairwise (·≤·)) :
    firstGap candidate count products=gapSpec candidate count products := by
  cases hc : count with
  | zero => simp only [firstGap,gapSpec,List.range'_zero,List.find?_nil]
  | succ count =>
    cases hp : products with
    | nil => simp only [firstGap,gapSpec,List.range'_succ,List.find?_cons,List.not_mem_nil,
        not_false_eq_true,decide_true]
    | cons y ys =>
      rw [hp] at hordered
      have hord := List.pairwise_cons.mp hordered
      rw [firstGap]
      by_cases hy : y<candidate
      · rw [if_pos hy,firstGap_eq_gapSpec candidate (count+1) ys hord.2]
        exact (gapSpec_skip_below hy).symm
      · rw [if_neg hy]
        by_cases he : y=candidate
        · rw [if_pos he,firstGap_eq_gapSpec (candidate+1) count ys hord.2]
          subst y
          unfold gapSpec
          rw [List.range'_succ,List.find?_cons]
          simp only [List.mem_cons_self,not_true_eq_false,decide_false]
          exact (gapSpec_skip_below (Nat.lt_succ_self candidate)).symm
        · rw [if_neg he]
          have hn : candidate∉y::ys := by
            intro hm
            rcases List.mem_cons.mp hm with hm|hm
            · omega
            · have hle := hord.1 candidate hm
              omega
          simp only [gapSpec,List.range'_succ,List.find?_cons,hn,not_false_eq_true,
            decide_true]
termination_by count+products.length
decreasing_by all_goals (simp_all only [List.length_cons]; omega)

/-- Complete first-missing-value specification on a public interval. -/
theorem gapSpec_eq_some_of_firstMissing (candidate count m : ℕ) (products : List ℕ)
    (hstart : candidate≤m) (hwindow : m<candidate+count) (hmissing : m∉products)
    (hbefore : ∀ x, candidate≤x → x<m → x∈products) :
    gapSpec candidate count products=some m := by
  induction count generalizing candidate with
  | zero => omega
  | succ count ih =>
    by_cases he : candidate=m
    · simp only [gapSpec,List.range'_succ,List.find?_cons,he,hmissing,
        not_false_eq_true,decide_true]
    · have hc : candidate∈products := hbefore candidate le_rfl (by omega)
      rw [gapSpec,List.range'_succ,List.find?_cons]
      simp only [hc,not_true_eq_false,decide_false]
      exact ih (candidate+1) (by omega) (by omega)
        (fun x hx hxm => hbefore x (by omega) hxm)

/-- Total public selector: sort all proper-product events in the doubled
window and expose its first missing candidate by the linear merge. -/
def publicSievePrime (B : ℕ) : ℕ :=
  (firstGap (max 2 B) (2*max 1 B+1-max 2 B) (sortedValues (2*max 1 B))).getD 2

/-- The sieve acquires exactly the previous public least prime. All
primality and firstness claims are discharged, not supplied as advice. -/
theorem publicSievePrime_eq_least (B : ℕ) (hB : 0<B) :
    publicSievePrime B=publicPrimeAtLeast B hB := by
  have hmax : max 1 B=B := max_eq_right hB
  have hp := publicPrimeAtLeast_prime B hB
  have hge := publicPrimeAtLeast_ge B hB
  have hle := publicPrimeAtLeast_le B hB
  have hs : max 2 B≤publicPrimeAtLeast B hB := max_le hp.two_le hge
  have hmissing : publicPrimeAtLeast B hB∉sortedValues (2*B) := by
    intro hm
    have he := (sortedValues_perm (2*B)).mem_iff.mp hm
    exact ((eventValues_mem_iff hp.two_le).mp he).2 hp
  have hbefore : ∀ x, max 2 B≤x → x<publicPrimeAtLeast B hB → x∈sortedValues (2*B) := by
    intro x hx hxm
    have hx2 : 2≤x := (le_max_left _ _).trans hx
    have hxB : B≤x := (le_max_right _ _).trans hx
    have hxX : x≤2*B := hxm.le.trans hle
    have hcomp : ¬x.Prime := by
      intro hprime
      exact (not_le_of_gt hxm) (publicPrimeAtLeast_minimal B hB hprime hxB)
    apply (sortedValues_perm (2*B)).mem_iff.mpr
    exact (eventValues_mem_iff hx2).mpr ⟨hxX,hcomp⟩
  have hgap : firstGap (max 2 B) (2*B+1-max 2 B) (sortedValues (2*B))=
      some (publicPrimeAtLeast B hB) := by
    rw [firstGap_eq_gapSpec _ _ _ (sortedValues_ordered _)]
    exact gapSpec_eq_some_of_firstMissing _ _ _ _ hs (by omega) hmissing hbefore
  simp only [publicSievePrime,hmax,hgap,Option.getD_some]

/-- Count actual merge invocations, including its terminal public guard.
This is not a Boolean or bit clock for the comparisons and list cells. -/
def firstGapIterations : (candidate count : ℕ) → List ℕ → ℕ
  | _,0,_ => 1
  | _,_+1,[] => 1
  | candidate,count+1,y::ys =>
    if y<candidate then 1+firstGapIterations candidate (count+1) ys
    else if y=candidate then 1+firstGapIterations (candidate+1) count ys else 1
termination_by _ count products => count+products.length
decreasing_by all_goals simp_wf <;> omega

theorem firstGapIterations_le (candidate count : ℕ) (products : List ℕ) :
    firstGapIterations candidate count products≤count+products.length+1 := by
  cases hc : count with
  | zero => simp only [firstGapIterations]; omega
  | succ count =>
    cases hp : products with
    | nil => simp only [firstGapIterations,List.length_nil]; omega
    | cons y ys =>
      rw [firstGapIterations]
      split_ifs with hy he
      · have h := firstGapIterations_le candidate (count+1) ys
        simp only [List.length_cons]
        omega
      · have h := firstGapIterations_le (candidate+1) count ys
        simp only [List.length_cons]
        omega
      · simp only [List.length_cons]
        omega
termination_by count+products.length
decreasing_by all_goals (simp_all only [List.length_cons]; omega)

/-- Sieve event construction and its final merge have uniform bounded
counts in the public doubled window. Sorting and bit costs remain separate. -/
theorem publicSieve_counts (B : ℕ) (hB : 0<B) :
    (properPairs (2*max 1 B)).length≤2*B*(Nat.log2 (2*B)+1)^2 ∧
      firstGapIterations (max 2 B) (2*max 1 B+1-max 2 B) (sortedValues (2*max 1 B))≤
        2*B*(Nat.log2 (2*B)+1)^2+2*B+2 := by
  rw [max_eq_right hB]
  refine ⟨properPairs_length_le _,?_⟩
  have hi := firstGapIterations_le (max 2 B) (2*B+1-max 2 B) (sortedValues (2*B))
  have hc := sortedValues_length_le (2*B)
  omega

/-- The N-only row modulus acquired by bounded proper-product events. -/
def sievedRowModulus (N : ℕ) : ℕ := publicSievePrime (max 1 (SemiprimeLehmanCoverage.sixthWidth N))

theorem sievedRowModulus_eq (N : ℕ) : sievedRowModulus N=publicRowModulus N :=
  publicSievePrime_eq_least _ (lt_of_lt_of_le (by decide : 0<1) (le_max_left _ _))

theorem sievedRowModulus_prime (N : ℕ) : (sievedRowModulus N).Prime := by
  rw [sievedRowModulus_eq]
  exact publicRowModulus_prime N

theorem sievedRowModulus_bounds {N : ℕ} (hN : 0<N) :
    SemiprimeLehmanCoverage.sixthWidth N≤sievedRowModulus N ∧
      sievedRowModulus N≤2*SemiprimeLehmanCoverage.sixthWidth N := by
  rw [sievedRowModulus_eq]
  exact publicRowModulus_bounds hN

/-- Modulus acquisition preserves the full ordinary, centered packet
list exactly; it changes no row, sign, center or multiplicity. -/
theorem sieved_publicPackets_eq (N : ℕ) :
    SemiprimeEuclidRowFamily.publicPackets N (sievedRowModulus N)=
      SemiprimeEuclidRowFamily.publicPackets N (publicRowModulus N) := by
  rw [sievedRowModulus_eq]

/-- Link the sieve-acquired public modulus to the complete shared
companion program, without either factor as an input. -/
noncomputable def recoverSievedCompanions (N : ℕ) : Option ℕ :=
  SemiprimeReflectedCompanions.recoverReflectedCompanions N (sievedRowModulus N)

theorem recoverSievedCompanions_eq (N : ℕ) : recoverSievedCompanions N=
    SemiprimeReflectedCompanions.recoverReflectedCompanions N (publicRowModulus N) := by
  rw [recoverSievedCompanions,sievedRowModulus_eq]

theorem recoverSievedCompanions_sound {N d : ℕ} (hd : recoverSievedCompanions N=some d) :
    SemiprimeGroupSelection.ProperDivisor N d :=
  SemiprimeReflectedCompanions.recoverReflectedCompanions_sound hd

/-- Literal public sieve modulus for the previous complete signed repair. -/
theorem control_sieved_modulus : sievedRowModulus 7303=5 := by
  have hu := SemiprimeLehmanCoverage.sixthWidth_upper 7303
  have hb : SemiprimeLehmanCoverage.sixthWidth 7303≤5 :=
    Nat.find_min' _ (by norm_num : 7303≤(5 : ℕ)^6)
  have hwidth : SemiprimeLehmanCoverage.sixthWidth 7303=5 := by
    by_contra hn
    have h4 : SemiprimeLehmanCoverage.sixthWidth 7303≤4 := by omega
    have hp := Nat.pow_le_pow_left h4 6
    norm_num at hp
    omega
  rw [sievedRowModulus,hwidth]
  change publicSievePrime 5=5
  rw [publicSievePrime_eq_least 5 (by norm_num)]
  apply (Nat.find_eq_iff _).mpr
  refine ⟨⟨by norm_num,le_rfl⟩,?_⟩
  intro m hm hp
  omega

theorem control_sieved_recovers : ∃ d, recoverSievedCompanions 7303=some d := by
  simpa only [recoverSievedCompanions,control_sieved_modulus] using
    SemiprimeReflectedCompanions.missed_control_reflected_recovers

open SemiprimeBitArithmetic SemiprimeBitDivision

/-- Retain both Boolean products and the full subtraction before the
ordering projection used by the public product sort. -/
structure ProductComparison where
  /-- Actual first factor-pair multiplication report. -/
  leftProduct : BitReport
  /-- Actual second factor-pair multiplication report. -/
  rightProduct : BitReport
  /-- Actual Boolean subtraction, including the final borrow. -/
  subtraction : SubReport
  /-- Negating the reverse-comparison borrow implements less or equal. -/
  lessEqual : Bool
  /-- Primitive clocks plus the final NOT gate and Boolean output cell. -/
  clock : ℕ

/-- No natural-value multiplication or ordering oracle computes this
predicate: both products and the borrow use the existing bit circuits. -/
def compareProductBits (a b c d : List Bool) : ProductComparison :=
  let left := mulBits a b
  let right := mulBits c d
  let sub := subBits right.bits left.bits false
  ⟨left,right,sub,!sub.borrow,bitCost left+bitCost right+bitCost sub.result+2⟩

/-- The priced Boolean primitive realizes exactly the public event-sort
predicate while preserving its product and subtraction reports. -/
theorem compareProductBits_correct (a b c d : List Bool) :
    (compareProductBits a b c d).lessEqual=true ↔
      bitValue a*bitValue b≤bitValue c*bitValue d := by
  have hs : (subBits (mulBits c d).bits (mulBits a b).bits false).borrow=true ↔
      bitValue c*bitValue d<bitValue a*bitValue b := by
    simpa only [bitNat,Bool.false_eq_true,if_false,Nat.add_zero,mulBits_correct] using
      subBits_borrow_iff (mulBits c d).bits (mulBits a b).bits false
  have hf : (subBits (mulBits c d).bits (mulBits a b).bits false).borrow=false ↔
      bitValue a*bitValue b≤bitValue c*bitValue d := by
    constructor
    · intro hb
      by_contra hn
      have ht := hs.mpr (by omega)
      rw [hb] at ht
      contradiction
    · intro hle
      cases hb : (subBits (mulBits c d).bits (mulBits a b).bits false).borrow with
      | false => rfl
      | true => have hlt := hs.mp hb; omega
  cases hb : (subBits (mulBits c d).bits (mulBits a b).bits false).borrow <;>
    simpa [compareProductBits,hb] using hf

/-- Every sort comparison has a quadratic primitive bit clock in the
physical factor-word width. Sorting and word construction are separate. -/
theorem compareProductBits_cost {L : ℕ} {a b c d : List Bool}
    (ha : a.length≤L) (hb : b.length≤L) (hc : c.length≤L) (hd : d.length≤L) :
    (compareProductBits a b c d).clock≤72*(L+1)^2 := by
  have hl := bounded_mulBits ha hb
  have hr := bounded_mulBits hc hd
  have hs := subBits_cost (mulBits c d).bits (mulBits a b).bits false
  have hw := max_le hr.2 hl.2
  have hsub : bitCost (subBits (mulBits c d).bits (mulBits a b).bits false).result≤36*L+2 := by
    have hmul := Nat.mul_le_mul_left 12 hw
    omega
  change bitCost (mulBits a b)+bitCost (mulBits c d)+
    bitCost (subBits (mulBits c d).bits (mulBits a b).bits false).result+2≤_
  nlinarith [hl.1,hr.1]

end RiemannGaussian.SemiprimePrimeSieve
