/-
Copyright (c) 2026 David Sanftenberg. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Sanftenberg
-/
import RiemannGaussian.SuzukiGammaNormalizedCurrent
import RiemannGaussian.ComplexGaussianCurvature

/-!
# A Gaussian square identity with the actual normalization retained

The normalized arithmetic curvature keeps a negative phase square and
the full denominator-drift allowance. Both are smooth through the
carrier divisor. Finite integration discharges all analytic hypotheses
for the actual fields and retains its exact current endpoints.
-/

open Complex Filter MeasureTheory Set Topology
open scoped ContDiff Interval
namespace RiemannGaussian
noncomputable section

/-- The normalized arithmetic current with its real Gaussian weight. -/
def suzukiGammaGaussianCurrent (r tau c y x : ℝ) : ℂ :=
  (translatedGaussian tau c x : ℂ) * (suzukiXiHorizontalMass r y x : ℂ) *
    suzukiGammaNormalizedSlope r y x

/-- The exact negative phase square after including denominator drift
and the derivative of the same Gaussian. -/
def suzukiGammaGaussianPhaseSquare (r tau c y x : ℝ) : ℝ :=
  translatedGaussian tau c x * ((suzukiGammaNormalizedSlope r y x).im +
    (suzukiGammaNormalizationDrift r y x +
      tau * (x - c) * suzukiXiHorizontalMass r y x) / 4) ^ 2

/-- The positive allowance generated by the complete denominator and
Gaussian derivatives; its arithmetic component is not discarded. -/
def suzukiGammaGaussianDriftAllowance (r tau c y x : ℝ) : ℝ :=
  translatedGaussian tau c x * (suzukiGammaNormalizationDrift r y x +
    tau * (x - c) * suzukiXiHorizontalMass r y x) ^ 2

private lemma gaussian_derivative (tau c x : ℝ) :
    HasDerivAt (translatedGaussian tau c)
      (-2 * tau * (x - c) * translatedGaussian tau c x) x := by
  convert ((((hasDerivAt_id x).sub_const c).pow 2).const_mul (-tau)).exp using 1
  · funext u
    simp only [translatedGaussian, Pi.pow_apply, id_eq]
  · simp only [translatedGaussian, Pi.pow_apply, id_eq]
    ring

private lemma gaussian_contDiff (tau c : ℝ) : ContDiff ℝ ∞ (translatedGaussian tau c) := by
  unfold translatedGaussian
  fun_prop

/-- The actual normalized Gaussian current is smooth across the
entire carrier divisor, including repeated zeros. -/
theorem contDiff_suzukiGammaGaussianCurrent {r y : ℝ} (hr : 0 < r) (hy : 0 ≤ y)
    (tau c : ℝ) : ContDiff ℝ ∞ (suzukiGammaGaussianCurrent r tau c y) :=
  ((Complex.ofRealCLM.contDiff.comp (gaussian_contDiff tau c)).mul
    (Complex.ofRealCLM.contDiff.comp (contDiff_suzukiXiHorizontalMass hr y))).mul
      (contDiff_suzukiGammaNormalizedSlope hr hy)

/-- The normalized arithmetic source has an exact Gaussian completed
square, with the full denominator drift present in both terms.
This holds through all repeated zeros and genuine carrier poles. -/
theorem suzukiGammaShiftArithmeticSource_gaussian_square {r y : ℝ}
    (hr : 0 < r) (hy : 0 ≤ y) (tau c x : ℝ) :
    translatedGaussian tau c x *
      (suzukiGammaShiftArithmeticSource r (suzukiGammaHorizontalArgument y x)).im =
      -2 * r ^ 2 * (deriv (suzukiGammaGaussianCurrent r tau c y) x).im -
        8 * r ^ 2 * suzukiGammaGaussianPhaseSquare r tau c y x +
          (r ^ 2 / 2) * suzukiGammaGaussianDriftAllowance r tau c y x := by
  have hU := ((contDiff_suzukiXiHorizontalMass hr y).differentiable (by simp) x).hasDerivAt.ofReal_comp
  have hT := ((contDiff_suzukiGammaNormalizedSlope hr hy).differentiable (by simp) x).hasDerivAt
  have hJ := (((gaussian_derivative tau c x).ofReal_comp.fun_mul hU).fun_mul hT).deriv
  change deriv (suzukiGammaGaussianCurrent r tau c y) x = _ at hJ
  rw [suzukiGammaShiftArithmeticSource_eq_normalized_current hr hy, hJ]
  rw [← ofReal_pow]
  simp only [mul_im, mul_re, sub_im, add_im, add_re, ofReal_im, ofReal_re,
    ofReal_mul, mul_zero, zero_mul, sub_zero, add_zero, zero_add,
    im_ofNat, re_ofNat]
  unfold suzukiGammaGaussianPhaseSquare suzukiGammaGaussianDriftAllowance suzukiGammaNormalizationDrift
  ring

private lemma square_continuous {r y : ℝ} (hr : 0 < r) (hy : 0 ≤ y) (tau c : ℝ) :
    Continuous (suzukiGammaGaussianPhaseSquare r tau c y) ∧
      Continuous (suzukiGammaGaussianDriftAllowance r tau c y) := by
  have hT := (contDiff_suzukiGammaNormalizedSlope hr hy).continuous
  have hU := (contDiff_suzukiXiHorizontalMass hr y).continuous
  have hD := (contDiff_suzukiGammaNormalizationDrift hr hy).continuous
  have hw := (gaussian_contDiff tau c).continuous
  have hv := Complex.continuous_im.comp hT
  have hc : Continuous (fun x => suzukiGammaNormalizationDrift r y x +
      tau * (x - c) * suzukiXiHorizontalMass r y x) :=
    hD.add ((continuous_const.mul (continuous_id.sub continuous_const)).mul hU)
  exact ⟨hw.mul ((hv.add (hc.div_const 4)).pow 2), hw.mul (hc.pow 2)⟩

/-- Both normalized Gaussian square terms are genuinely integrable
on every finite interval, including across the full carrier divisor. -/
theorem intervalIntegrable_suzukiGammaGaussian_squares {r y : ℝ}
    (hr : 0 < r) (hy : 0 ≤ y) (tau c a b : ℝ) :
    IntervalIntegrable (suzukiGammaGaussianPhaseSquare r tau c y) volume a b ∧
      IntervalIntegrable (suzukiGammaGaussianDriftAllowance r tau c y) volume a b :=
  ⟨(square_continuous hr hy tau c).1.intervalIntegrable a b,
    (square_continuous hr hy tau c).2.intervalIntegrable a b⟩

/-- The exact normalized square identity on an arbitrary finite
interval retains both current endpoints, its negative square and the
entire positive denominator-drift allowance. -/
theorem integral_suzukiGammaShiftArithmeticSource_gaussian_square {r y : ℝ}
    (hr : 0 < r) (hy : 0 ≤ y) (tau c a b : ℝ) :
    (∫ x : ℝ in a..b, translatedGaussian tau c x *
      (suzukiGammaShiftArithmeticSource r (suzukiGammaHorizontalArgument y x)).im) =
      -2 * r ^ 2 * (suzukiGammaGaussianCurrent r tau c y b - suzukiGammaGaussianCurrent r tau c y a).im -
        8 * r ^ 2 * (∫ x : ℝ in a..b, suzukiGammaGaussianPhaseSquare r tau c y x) +
          (r ^ 2 / 2) * (∫ x : ℝ in a..b, suzukiGammaGaussianDriftAllowance r tau c y x) := by
  have hJ := contDiff_suzukiGammaGaussianCurrent hr hy tau c
  have hd : IntervalIntegrable (deriv (suzukiGammaGaussianCurrent r tau c y)) volume a b :=
    (hJ.continuous_deriv (by simp)).intervalIntegrable a b
  have hdi : IntervalIntegrable (fun x => (deriv (suzukiGammaGaussianCurrent r tau c y) x).im) volume a b :=
    (Complex.continuous_im.comp (hJ.continuous_deriv (by simp))).intervalIntegrable a b
  have hsq := intervalIntegrable_suzukiGammaGaussian_squares hr hy tau c a b
  have he := intervalIntegral.integral_deriv_eq_sub
    (fun x _ => hJ.differentiable (by simp) x) hd
  have him : (∫ x : ℝ in a..b, (deriv (suzukiGammaGaussianCurrent r tau c y) x).im) =
      (suzukiGammaGaussianCurrent r tau c y b - suzukiGammaGaussianCurrent r tau c y a).im := by
    have hh := Complex.imCLM.intervalIntegral_comp_comm hd
    simp only [Complex.imCLM_apply] at hh
    rw [hh, he]
  simp_rw [suzukiGammaShiftArithmeticSource_gaussian_square hr hy tau c]
  rw [intervalIntegral.integral_add ((hdi.const_mul _).sub (hsq.1.const_mul _)) (hsq.2.const_mul _),
    intervalIntegral.integral_sub (hdi.const_mul _) (hsq.1.const_mul _)]
  simp only [intervalIntegral.integral_const_mul, him]

/-- The true normalized arithmetic curvature has this independent
finite-interval upper bound. Its positive allowance explicitly contains
the denominator drift; no decay of that allowance is presumed. -/
theorem integral_suzukiGammaShiftArithmeticSource_gaussian_le_drift {r y a b : ℝ}
    (hr : 0 < r) (hy : 0 ≤ y) (hab : a ≤ b) (tau c : ℝ) :
    (∫ x : ℝ in a..b, translatedGaussian tau c x *
      (suzukiGammaShiftArithmeticSource r (suzukiGammaHorizontalArgument y x)).im) ≤
      -2 * r ^ 2 * (suzukiGammaGaussianCurrent r tau c y b - suzukiGammaGaussianCurrent r tau c y a).im +
        (r ^ 2 / 2) * (∫ x : ℝ in a..b, suzukiGammaGaussianDriftAllowance r tau c y x) := by
  rw [integral_suzukiGammaShiftArithmeticSource_gaussian_square hr hy tau c a b]
  have hp : 0 ≤ ∫ x : ℝ in a..b, suzukiGammaGaussianPhaseSquare r tau c y x := by
    apply intervalIntegral.integral_nonneg hab
    intro x _
    unfold suzukiGammaGaussianPhaseSquare translatedGaussian
    positivity
  nlinarith [mul_nonneg (sq_nonneg r) hp]

end
end RiemannGaussian
