/-
Copyright (c) 2026 David Sanftenberg. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Sanftenberg
-/
import RiemannGaussian.ZetaRieszSmoothPrimeProduct

/-!
# Actual one-large-prime classes on the physical prefix

Unique prime insertion identifies the finite pair sum with the actual
integer class. Every squarefree cofactor supported through N^2 is retained,
and every order-dependent subband mask is allowed. All scalar conditions
are discharged for 1/2<u<exp(-1/2). Other source scales and primes beyond
the physical cutoff remain outside this component estimate.
-/

namespace RiemannGaussian.ZetaRieszSmoothPrimePrefix
noncomputable section
open Filter Topology
open scoped BigOperators Classical
open ZetaRieszSmoothPrimeProduct

/-- A genuine integer class generated by finite prime/cofactor pairs,
then intersected with the original logarithmic band and an arbitrary subband mask. -/
def productBand (keep : ℕ → Prop) (A Q : Finset ℕ) (N : ℕ) : Finset ℕ :=
  ((A ×ˢ Q).image (fun ap => ap.2 * ap.1)).filter (fun n => n ∈ zetaPrimeLogBand N ∧ keep n)

/-- A prime above the full cofactor head is uniquely recoverable from
the product. Thus the signed pair sum counts each integer exactly once. -/
theorem productBand_sum_eq_pairResponse (keep : ℕ → Prop) (A Q : Finset ℕ) (P : Polynomial ℂ) (N b : ℕ) (y L : ℝ)
    (hA : ∀ a ∈ A, Squarefree a)
    (hsmall : ∀ a ∈ A, ∀ p ∈ a.primeFactors, p ≤ b)
    (hQ : ∀ p ∈ Q, p.Prime ∧ b < p) :
    (∑ n ∈ productBand keep A Q N, SquarefreeVaughanLogSource.coefficient L n *
      zetaPrimeFilterKernel P N (3 / 2 + Complex.I * y) n) = pairResponse keep A Q P N y L := by
  have hinj : Set.InjOn (fun ap : ℕ × ℕ => ap.2 * ap.1) (A ×ˢ Q : Finset (ℕ × ℕ)) := by
    rintro ⟨a, p⟩ hap ⟨c, r⟩ hcr he
    obtain ⟨ha, hp⟩ := Finset.mem_product.mp hap
    obtain ⟨hc, hr⟩ := Finset.mem_product.mp hcr
    change p * a = r * c at he
    have hpd : p ∣ r * c := by rw [← he]; exact dvd_mul_right p a
    have hpc : ¬ p ∣ c := by
      intro hd
      have hm := Nat.mem_primeFactors.mpr ⟨(hQ p hp).1, hd, (hA c hc).ne_zero⟩
      exact ((hQ p hp).2.not_ge) (hsmall c hc p hm)
    have hpr : p = r := (Nat.prime_dvd_prime_iff_eq (hQ p hp).1 (hQ r hr).1).mp
      (((hQ p hp).1.dvd_mul.mp hpd).resolve_right hpc)
    subst r
    have hac : a = c := mul_left_cancel₀ (hQ p hp).1.ne_zero he
    exact Prod.ext hac rfl
  unfold productBand
  rw [Finset.sum_filter, Finset.sum_image hinj, Finset.sum_product]
  rfl

/-- Every squarefree cofactor supported through b appears in this
literal finite divisor set; there is no imposed cofactor-size truncation. -/
def cofactorHead (b : ℕ) : Finset ℕ := (primorial b).divisors

/-- The full primorial cofactor head consists of squarefree integers. -/
theorem cofactorHead_squarefree (b : ℕ) : ∀ a ∈ cofactorHead b, Squarefree a := by
  intro a ha
  exact (squarefree_primorial b).squarefree_of_dvd (Nat.dvd_of_mem_divisors ha)

/-- Every prime of every cofactor in the full head lies in the
literal prime head, with no bound on the total cofactor size. -/
theorem cofactorHead_primeFactors (b : ℕ) :
    ∀ a ∈ cofactorHead b, a.primeFactors ⊆ Nat.primesLE b := by
  intro a ha
  simpa only [primeFactors_primorial] using
    Nat.primeFactors_mono (Nat.dvd_of_mem_divisors ha) (primorial_ne_zero b)

/-- The distinguished prime lies above the smooth head and inside
the unchanged physical Riesz cutoff. -/
def physicalPrimePrefix (u : ℝ) (N : ℕ) : Finset ℕ :=
  (Nat.primesLE ((ZetaVaughanCutoffBudget.linearDampedCutoff u N + 2) ^ 2)).filter
    (fun p => N ^ 2 < p)

/-- The actual class with one distinguished prime on the physical
prefix and an arbitrary-size smooth cofactor. Each label appears once. -/
def actualProductBand (keep : ℕ → Prop) (u : ℝ) (N : ℕ) : Finset ℕ :=
  productBand keep (cofactorHead (N ^ 2)) (physicalPrimePrefix u N) N

/-- The complete original integer-class sum is the checked pair sum,
with uniqueness of prime insertion and every source cutoff retained. -/
theorem actualProductBand_sum_eq_pairResponse (keep : ℕ → Prop) (P : Polynomial ℂ) (N : ℕ) (y L u : ℝ) :
    (∑ n ∈ actualProductBand keep u N, SquarefreeVaughanLogSource.coefficient L n *
      zetaPrimeFilterKernel P N (3 / 2 + Complex.I * y) n) =
      pairResponse keep (cofactorHead (N ^ 2)) (physicalPrimePrefix u N) P N y L := by
  apply productBand_sum_eq_pairResponse keep _ _ P N (N ^ 2) y L (cofactorHead_squarefree _)
  · intro a ha p hp
    exact (Nat.mem_primesLE.mp (cofactorHead_primeFactors (N ^ 2) a ha hp)).1
  · intro p hp
    exact ⟨(Nat.mem_primesLE.mp (Finset.mem_filter.mp hp).1).2, (Finset.mem_filter.mp hp).2⟩

/-- A strict admissible tilt independently pays this entire actual
one-large-prime class with every smooth cofactor size. All premises are
explicit scalar conditions; no arithmetic-tail bound is assumed. -/
theorem tendsto_actualProductBand (keep : ℕ → ℕ → Prop) (P : Polynomial ℂ) (y : ℝ)
    {u q : ℝ} (hu : 0 < u) (hu1 : u ≤ 1) (hq : 1 / 2 < q) (hq1 : q ≤ 1)
    (hrate : ZetaRieszCofactorTiltRate.tiltRate u q < 1) :
    Tendsto (fun N : ℕ => (u : ℂ) ^ (N + 1) *
      ∑ n ∈ actualProductBand (keep N) u N,
        SquarefreeVaughanLogSource.coefficient (SquarefreeVaughanLogSource.length u N) n *
          zetaPrimeFilterKernel P N (3 / 2 + Complex.I * y) n) atTop (nhds 0) := by
  have h := tendsto_quadratic_pairResponse keep (fun N => cofactorHead (N ^ 2))
    (physicalPrimePrefix u) (fun N => Nat.primesLE (N ^ 2)) P y
    (fun N => cofactorHead_squarefree (N ^ 2)) (fun N => cofactorHead_primeFactors (N ^ 2))
    (fun _N _p hp => ⟨(Nat.mem_primesLE.mp hp).2, (Nat.mem_primesLE.mp hp).1⟩)
    hu hu1 hq hq1 (fun _N _p hp =>
      ⟨(Nat.mem_primesLE.mp (Finset.mem_filter.mp hp).1).2,
        (Nat.mem_primesLE.mp (Finset.mem_filter.mp hp).1).1⟩) hrate
  simpa only [actualProductBand_sum_eq_pairResponse] using h

/-- The primorial head includes exactly all squarefree cofactors
whose prime divisors lie through the head threshold. -/
theorem mem_cofactorHead_iff (b a : ℕ) :
    a ∈ cofactorHead b ↔ Squarefree a ∧ ∀ p ∈ a.primeFactors, p ≤ b := by
  constructor
  · intro ha
    exact ⟨cofactorHead_squarefree b a ha, fun p hp =>
      (Nat.mem_primesLE.mp (cofactorHead_primeFactors b a ha hp)).1⟩
  · rintro ⟨ha, hp⟩
    have hsub : a.primeFactors ⊆ (primorial b).primeFactors := by
      rw [primeFactors_primorial]
      intro p hpa
      exact Nat.mem_primesLE.mpr ⟨hp p hpa, Nat.prime_of_mem_primeFactors hpa⟩
    have hd := (Nat.prod_primeFactors_dvd_iff (primorial_ne_zero b)).mpr hsub
    rw [Nat.prod_primeFactors_of_squarefree ha] at hd
    exact Nat.mem_divisors.mpr ⟨hd, primorial_ne_zero b⟩

/-- A whole interval of source scales has a proved strict tilt saving
inside the quadratic-head half-plane. No unspecified scalar rate remains. -/
theorem exists_quadratic_head_tilt {u : ℝ} (hu : 1 / 2 < u)
    (hcontact : u < Real.exp (-(1 / 2 : ℝ))) :
    ∃ q : ℝ, 1 / 2 < q ∧ q ≤ 1 ∧ ZetaRieszCofactorTiltRate.tiltRate u q < 1 := by
  have hu0 : 0 < u := by linarith
  have hu1 : u < 1 := hcontact.trans (Real.exp_lt_one_iff.mpr (by norm_num))
  have hl : Real.log u < -(1 / 2 : ℝ) := by
    have h := Real.log_lt_log hu0 hcontact
    rwa [Real.log_exp] at h
  have hd : 1 < -2 * Real.log u := by linarith
  refine ⟨ZetaRieszCofactorTiltRate.optimalTilt u,
    ZetaRieszCofactorTiltRate.optimalTilt_gt_half hu hu1, ?_, ?_⟩
  · exact (div_le_one (by linarith : 0 < -2 * Real.log u)).mpr hd.le
  · exact (ZetaRieszCofactorTiltRate.tiltRate_optimal hu0 hu1).trans_lt
      (ZetaRieszCofactorTiltRate.minimumRate_lt_one hu0 hcontact.ne)

/-- The whole actual one-large-prime class on the physical prefix
decays independently for 1/2<u<exp(-1/2), with every smooth cofactor size.
The larger-prime tail and other source scales are outside this assertion. -/
theorem tendsto_actualProductBand_of_small_source (keep : ℕ → ℕ → Prop) (P : Polynomial ℂ) (y : ℝ)
    {u : ℝ} (hu : 1 / 2 < u) (hcontact : u < Real.exp (-(1 / 2 : ℝ))) :
    Tendsto (fun N : ℕ => (u : ℂ) ^ (N + 1) *
      ∑ n ∈ actualProductBand (keep N) u N,
        SquarefreeVaughanLogSource.coefficient (SquarefreeVaughanLogSource.length u N) n *
          zetaPrimeFilterKernel P N (3 / 2 + Complex.I * y) n) atTop (nhds 0) := by
  obtain ⟨q, hq, hq1, hrate⟩ := exists_quadratic_head_tilt hu hcontact
  exact tendsto_actualProductBand keep P y (show 0 < u by linarith)
    ((hcontact.trans (Real.exp_lt_one_iff.mpr (by norm_num))).le) hq hq1 hrate

/-- Exact membership in the independently bounded integer class:
one prime is above N^2 and below the original physical cutoff, and all
prime factors of its squarefree cofactor lie in the quadratic head. -/
theorem mem_actualProductBand_iff (keep : ℕ → Prop) (u : ℝ) (N n : ℕ) :
    n ∈ actualProductBand keep u N ↔ (n ∈ zetaPrimeLogBand N ∧ keep n) ∧ ∃ a p : ℕ,
      Squarefree a ∧ (∀ r ∈ a.primeFactors, r ≤ N ^ 2) ∧ p.Prime ∧ N ^ 2 < p ∧
      p ≤ (ZetaVaughanCutoffBudget.linearDampedCutoff u N + 2) ^ 2 ∧ n = p * a := by
  constructor
  · intro hn
    obtain ⟨hi, hb⟩ := Finset.mem_filter.mp hn
    obtain ⟨⟨a, p⟩, hap, he⟩ := Finset.mem_image.mp hi
    obtain ⟨ha, hp⟩ := Finset.mem_product.mp hap
    obtain ⟨hpa, hpb⟩ := Finset.mem_filter.mp hp
    obtain ⟨hple, hpprime⟩ := Nat.mem_primesLE.mp hpa
    obtain ⟨hasf, hasmall⟩ := (mem_cofactorHead_iff (N ^ 2) a).mp ha
    exact ⟨hb, a, p, hasf, hasmall, hpprime, hpb, hple, he.symm⟩
  · rintro ⟨hb, a, p, hasf, hasmall, hpprime, hpb, hple, he⟩
    apply Finset.mem_filter.mpr
    refine ⟨Finset.mem_image.mpr ⟨(a, p), ?_, he.symm⟩, hb⟩
    exact Finset.mem_product.mpr ⟨(mem_cofactorHead_iff (N ^ 2) a).mpr ⟨hasf, hasmall⟩,
      Finset.mem_filter.mpr ⟨Nat.mem_primesLE.mpr ⟨hple, hpprime⟩, hpb⟩⟩

end
end RiemannGaussian.ZetaRieszSmoothPrimePrefix
