import RiemannGaussian.MontgomeryTaylorIntegerCover
import RiemannGaussian.CertificateData.MontgomeryTaylorCover
import RiemannGaussian.External.Zeta23SevenWindowIntegerCertificate
import RiemannGaussian.MontgomeryTaylorIntegerBoxCertificate
import RiemannGaussian.CertificateData.MontgomeryTaylorIntegerRanges
import RiemannGaussian.CertificateData.MontgomeryTaylorIntegerAnchors
import RiemannGaussian.CertificateData.MontgomeryTaylorAnchors
import RiemannGaussian.CertificateData.MontgomeryTaylorAnchors00
import RiemannGaussian.CertificateData.MontgomeryTaylorAnchors01
import RiemannGaussian.CertificateData.MontgomeryTaylorAnchors02
import RiemannGaussian.CertificateData.MontgomeryTaylorAnchors03
import RiemannGaussian.CertificateData.MontgomeryTaylorAnchors04
import RiemannGaussian.CertificateData.MontgomeryTaylorAnchors05
import RiemannGaussian.CertificateData.MontgomeryTaylorAnchors06
import RiemannGaussian.CertificateData.MontgomeryTaylorAnchors07
import RiemannGaussian.CertificateData.MontgomeryTaylorPhaseCycle
import RiemannGaussian.CertificateData.MontgomeryTaylorRangeCells
import RiemannGaussian.CertificateData.MontgomeryTaylorRangeCells00
import RiemannGaussian.CertificateData.MontgomeryTaylorRangeCells01
import RiemannGaussian.CertificateData.MontgomeryTaylorRangeCells02
import RiemannGaussian.CertificateData.MontgomeryTaylorRangeCells03
import RiemannGaussian.CertificateData.MontgomeryTaylorRangeCells04
import RiemannGaussian.CertificateData.MontgomeryTaylorRangeCells05
import RiemannGaussian.CertificateData.MontgomeryTaylorRangeCells06
import RiemannGaussian.CertificateData.MontgomeryTaylorRangeCells07
import RiemannGaussian.External.Zeta23SevenWindowCertificate
import RiemannGaussian.MontgomeryTaylorAnchorBounds
import RiemannGaussian.MontgomeryTaylorBoxCertificate
import RiemannGaussian.MontgomeryTaylorCurvatureCertificate
import RiemannGaussian.MontgomeryTaylorFastCurvature
import RiemannGaussian.MontgomeryTaylorIntegerCoordinates
import RiemannGaussian.MontgomeryTaylorPointBounds
import RiemannGaussian.MontgomeryTaylorRangeTable

/-!
# Optional numerical certificate verification

Build explicitly with `lake build NumericalCertificate --wfail`. The expensive
tables and eventual exhaustive cover are excluded from the default library.
The complete cover proves the 6731/10000 endpoint for literal eventual dyadic
and cumulative simple critical-line zero counts.
-/
