#!/usr/bin/env python3
"""Propose reusable anchor certificates, each checked separately in Lean.

Copyright (c) 2026 David Sanftenberg. Released under Apache 2.0.
Both input files and this data generator are untrusted. Every generated
anchor proof checks all nineteen point enclosures and its cached summaries.
"""
import argparse
from fractions import Fraction
from pathlib import Path


def integer(value: int) -> str:
    return f"Int.ofNat {value}" if value >= 0 else f"Int.negSucc {-value - 1}"


def rational(value: Fraction) -> str:
    return f"(({integer(value.numerator)} : ℤ) : ℚ) / {value.denominator}"


def floor(value: Fraction) -> int:
    return value.numerator // value.denominator


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("points", type=Path)
    parser.add_argument("samples", type=Path)
    args = parser.parse_args()
    points = [list(map(int, row.split())) for row in args.points.read_text().splitlines()]
    if len(points) != 944 or any(len(p) != 6 for p in points):
        raise ValueError("Expected exactly 944 six-coordinate anchor proposals")
    samples = [list(map(int, row.split())) for row in args.samples.read_text().splitlines()]
    if any(len(row) != 6 for row in samples) or [(r[0], r[1]) for r in samples] != [
            (i, t) for i in range(944) for t in range(19)]:
        raise ValueError("Expected every anchor's nineteen samples in order")
    pairs = [(i, s, Fraction(v, 100000)) for s, row in enumerate([
        [21884, 33405, 44711, 44711, 33405, 21884],
        [74396, 25604, 0, 25604, 74396], [32469, 67531, 67531, 32469],
        [100000, 0, 100000], [100000, 100000], [200000]], 1)
        for i, v in enumerate(row) if v]
    pressure = [Fraction(v, 10**9) for v in [208856, 325508, 465636, 465636, 325508, 208856]]
    scale = 2**40
    target = Path(__file__).resolve().parents[1] / "RiemannGaussian/CertificateData"
    header = '''/-
Copyright (c) 2026 David Sanftenberg. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Sanftenberg
-/
'''

    def membership_proof(names: list[str], predicate: str) -> str:
        result = "  intro a ha\n  simp only [" + predicate + ", List.mem_cons, List.not_mem_nil, or_false] at ha\n"
        result += "  rcases ha with " + " | ".join("rfl" for _ in names) + "\n"
        return result + "".join(f"  · exact {name}_valid\n" for name in names)

    for group in range(8):
        left, right = group * 128, min((group + 1) * 128, 944)
        namespace = f"RiemannGaussian.MontgomeryTaylorAnchorBounds.CertificateData.Group{group:02d}"
        text = header + '''import RiemannGaussian.MontgomeryTaylorAnchorBounds

/-!
# Kernel-checked reusable seven-point anchors

Generated by `scripts/generate_montgomery_taylor_anchor_data.py`.
Every real value and full signed gradient enclosure follows from the kernel
check of its nineteen pair samples, independently of any box search.
-/

''' + f"namespace {namespace}\n\nset_option maxRecDepth 100000\nset_option maxHeartbeats 0\n\n"
        names = []
        for index in range(left, right):
            name = f"anchor{index:03d}"
            names.append(name)
            point = [Fraction(x, 10**7) for x in points[index]]
            rows = samples[index * 19:(index + 1) * 19]
            value = sum(pressure[j] * point[j] for j in range(6))
            lower, upper = pressure.copy(), pressure.copy()
            for (start, length, coeff), (_, _, _, v, dl, du) in zip(pairs, rows):
                value += coeff * Fraction(v, scale)
                for j in range(start, start + length):
                    lower[j] += coeff * Fraction(dl, scale)
                    upper[j] += coeff * Fraction(du, scale)
            value = Fraction(floor(value * scale), scale)
            lower = [Fraction(floor(v * scale), scale) for v in lower]
            upper = [Fraction(-floor(-v * scale), scale) for v in upper]
            text += f"private def {name} : Anchor := {{\n"
            text += "  point := ![" + ", ".join(map(rational, point)) + "],\n"
            text += "  value := " + rational(value) + ",\n"
            text += "  lower := ![" + ", ".join(map(rational, lower)) + "],\n"
            text += "  upper := ![" + ", ".join(map(rational, upper)) + "] }\n\n"
            text += f"private def {name}Witness : Witness := {{\n"
            text += "  phase := ![" + ", ".join(str(r[2]) for r in rows) + "],\n"
            text += "  samples := ![" + ",\n    ".join(
                "{ value := " + integer(v) + ", derivativeLo := " + integer(dl) +
                ", derivativeHi := " + integer(du) + " }" for _, _, _, v, dl, du in rows) + "] }\n\n"
            text += f"private theorem {name}_valid : Valid {name} :=\n"
            text += f"  check_sound (show check {name} {name}Witness = true from by decide +kernel)\n\n"
        blocks = []
        for number, start in enumerate(range(0, len(names), 32)):
            block = f"block{number:02d}"
            members = names[start:start + 32]
            blocks.append(block)
            text += f"private def {block} : List Anchor := [" + ", ".join(members) + "]\n\n"
            text += f"private theorem {block}_valid : ∀ a ∈ {block}, Valid a := by\n"
            text += membership_proof(members, block) + "\n"
        text += "/-- Consecutive chunks of independently certified reusable anchors. -/\n"
        text += "def blocks : List (List Anchor) := [" + ", ".join(blocks) + "]\n\n"
        text += "/-- Every entry of every stored chunk has its real analytic interpretation. -/\n"
        text += "theorem blocks_valid : ∀ block ∈ blocks, ∀ a ∈ block, Valid a := by\n"
        text += membership_proof(blocks, "blocks") + f"\nend {namespace}\n"
        (target / f"MontgomeryTaylorAnchors{group:02d}.lean").write_text(text)
    imports = "\n".join(f"import RiemannGaussian.CertificateData.MontgomeryTaylorAnchors{i:02d}"
                        for i in range(8))
    text = header + imports + '''

/-!
# The complete certified anchor catalogue

All stored objective and gradient enclosures have passed Lean's kernel.
This catalogue supports a future exhaustive box certificate; it does not
by itself establish the proposed zeta zero-count improvement.
-/

namespace RiemannGaussian.MontgomeryTaylorAnchorBounds.CertificateData

/-- The complete catalogue in short indexed blocks. -/
def blocks : List (List Anchor) :=
  ''' + " ++ ".join(f"Group{i:02d}.blocks" for i in range(8)) + '''

/-- Every available anchor has a proved real value and gradient enclosure. -/
theorem blocks_valid : ∀ block ∈ blocks, ∀ a ∈ block, Valid a := by
  intro block hb
  simp only [blocks, List.mem_append, or_assoc] at hb
  rcases hb with ''' + " | ".join(f"h{i}" for i in range(8)) + "\n"
    text += "".join(f"  · exact Group{i:02d}.blocks_valid block h{i}\n" for i in range(8))
    text += '''
/-- The optional lookup used by the exhaustive checker. -/
def lookup (i : ℕ) : Option Anchor := catalogueLookup blocks i

/-- A successful catalogue lookup returns a fully certified anchor. -/
theorem lookup_valid (i : ℕ) (a : Anchor) (h : lookup i = some a) : Valid a :=
  catalogueLookup_valid blocks blocks_valid h

end RiemannGaussian.MontgomeryTaylorAnchorBounds.CertificateData
'''
    (target / "MontgomeryTaylorAnchors.lean").write_text(text)
    print("Generated 944 proposed anchors in eight independently checked groups")


if __name__ == "__main__":
    main()
