#!/usr/bin/env python3
"""Propose continuous range-table data, all separately checked in Lean.

Copyright (c) 2026 David Sanftenberg. Released under Apache 2.0.
Input is the TSV emitted by scripts/GenerateMontgomeryTaylorRangeTable.lean.
Neither this script nor the producing executable belongs to the trusted proof.
"""
import argparse
from pathlib import Path


def integer(value: int) -> str:
    return f"Int.ofNat {value}" if value >= 0 else f"Int.negSucc {-value - 1}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tsv", type=Path)
    args = parser.parse_args()
    values = {}
    for line in args.tsv.read_text().splitlines():
        index, value, curvature = map(int, line.split())
        if index in values:
            raise ValueError(f"Repeated cell {index}")
        values[index] = (value, curvature)
    if set(values) != set(range(166, 9472)):
        raise ValueError("The input must contain exactly the cells 166 through 9471")
    target = Path(__file__).resolve().parents[1] / "RiemannGaussian/CertificateData"
    target.mkdir(parents=True, exist_ok=True)
    header = '''/-
Copyright (c) 2026 David Sanftenberg. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Sanftenberg
-/
'''

    def bound(left: int, right: int) -> str:
        low_value = min(values[i][0] for i in range(left, right))
        low_curvature = min(values[i][1] for i in range(left, right))
        return f"({integer(low_value)}, {integer(low_curvature)})"

    def literal_tree(left: int, right: int) -> str:
        b = bound(left, right)
        if left + 1 == right:
            return f"(.leaf {b} {16 * left + 8})"
        mid = (left + right) // 2
        return (f"(.node {b} ({mid} / 500)\n  "
                f"{literal_tree(left, mid)}\n  {literal_tree(mid, right)})")

    def compose(parts: list[tuple[str, int, int]]) -> tuple[str, str]:
        if len(parts) == 1:
            name, _, _ = parts[0]
            return name, name + "_checked"
        half = len(parts) // 2
        lt, lp = compose(parts[:half])
        rt, rp = compose(parts[half:])
        b = bound(parts[0][1], parts[-1][2])
        mid = parts[half][1]
        return (f"(.node {b} ({mid} / 500) {lt} {rt})",
                f"check_node ({lp}) ({rp}) (by decide +kernel) (by decide +kernel)")

    segments = [(i, min(i + 128, 9472)) for i in range(166, 9472, 128)]
    modules = []
    for group in range(8):
        selected = segments[group * len(segments) // 8:(group + 1) * len(segments) // 8]
        name = f"MontgomeryTaylorRangeCells{group:02d}"
        namespace = f"RiemannGaussian.MontgomeryTaylorRangeTable.CertificateData.Group{group:02d}"
        text = header + '''import RiemannGaussian.MontgomeryTaylorRangeTable

/-!
# Kernel-checked continuous value and curvature cells

Generated by `scripts/generate_montgomery_taylor_range_data.py`.
Every leaf and every cache comparison is checked by the Lean kernel.
-/

''' + f"namespace {namespace}\n\nset_option maxRecDepth 100000\nset_option maxHeartbeats 0\n\n"
        parts = []
        for number, (left, right) in enumerate(selected):
            chunk = f"chunk{number:02d}"
            text += (f"private def {chunk} : Table :=\n{literal_tree(left, right)}\n\n"
                     f"private theorem {chunk}_checked : check {chunk} ({left} / 500) "
                     f"({right} / 500) = true := by decide +kernel\n\n")
            parts.append((chunk, left, right))
        tree, proof = compose(parts)
        left, right = selected[0][0], selected[-1][1]
        text += ("/-- The complete continuous table for this consecutive group of cells. -/\n"
                 f"def table : Table :=\n{tree}\n\n"
                 "/-- Every cell and every cache entry in this group passes the kernel check. -/\n"
                 f"theorem table_checked : check table ({left} / 500) ({right} / 500) = true :=\n"
                 f"  {proof}\n\nend {namespace}\n")
        (target / (name + ".lean")).write_text(text)
        modules.append((f"Group{group:02d}.table", left, right))
    tree, proof = compose(modules)
    imports = "\n".join(f"import RiemannGaussian.CertificateData.MontgomeryTaylorRangeCells{i:02d}"
                        for i in range(8))
    text = header + imports + '''

/-!
# The complete kernel-checked continuous range table

The 9306 consecutive cells cover all real separations from `166/500` to
`9472/500`. The table controls both squared value and signed curvature.
It is one component of the proposed seven-point certificate, not by itself
a proved improvement of the zeta zero-count proportion.
-/

namespace RiemannGaussian.MontgomeryTaylorRangeTable.CertificateData

set_option maxRecDepth 100000
set_option maxHeartbeats 0

/-- The complete continuous value and curvature table. -/
def table : Table :=
''' + tree + '''

/-- All continuous cells and all cached range bounds pass the Lean kernel. -/
theorem table_checked : check table (166 / 500) (9472 / 500) = true :=
  ''' + proof + '''

/-- The complete continuous analytic meaning of the stored range table. -/
theorem table_valid : Valid table (166 / 500) (9472 / 500) := check_sound table_checked

end RiemannGaussian.MontgomeryTaylorRangeTable.CertificateData
'''
    (target / "MontgomeryTaylorRangeCells.lean").write_text(text)
    print(f"Generated {len(values)} cells in eight independently checked groups")


if __name__ == "__main__":
    main()
