#!/usr/bin/env python3
"""Generate integer phase witnesses; Lean separately checks every residual.

Copyright (c) 2026 David Sanftenberg. Released under Apache 2.0.
This script is a data generator, not part of the trusted proof.
"""
from pathlib import Path


def lean_int(value: int) -> str:
    """Avoid thousands of overloaded negative-literal elaboration problems."""
    return f"Int.ofNat {value}" if value >= 0 else f"Int.negSucc {-value - 1}"


def main() -> None:
    scale = 10**18
    base_cos = 999999922893716607
    base_sin = 392699071605535
    points = [(scale, 0)]
    for _ in range(15999):
        c, s = points[-1]
        points.append(((base_cos * c - base_sin * s) // scale,
                       (base_sin * c + base_cos * s) // scale))
    target = Path(__file__).resolve().parents[1] / (
        "RiemannGaussian/CertificateData/MontgomeryTaylorPhaseCycle.lean")
    target.parent.mkdir(parents=True, exist_ok=True)
    preamble = '''/-
Copyright (c) 2026 David Sanftenberg. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Sanftenberg
-/
import RiemannGaussian.MontgomeryTaylorPhaseTable
import RiemannGaussian.UniformBlockIndex

/-!
# Kernel-checked integer witnesses for one full phase cycle

Generated by `scripts/generate_montgomery_taylor_phase_cycle.py`.
The generator is untrusted: the proofs below check every integer residual.
Periodicity then gives the same error bound at every natural grid index.
-/

namespace RiemannGaussian.MontgomeryTaylorPhaseGrid.CertificateData

set_option maxRecDepth 100000
set_option maxHeartbeats 0

'''
    chunks = []
    names = []
    for start in range(0, len(points), 1000):
        name = f"part{start // 1000:02d}"
        names.append(name)
        data = ",\n".join(f"  ({lean_int(c)}, {lean_int(s)})"
                          for c, s in points[start:start + 1000])
        chunks.append(f"private def {name} : List (ℤ × ℤ) := [\n{data}\n]\n"
                      f"private theorem {name}_length : {name}.length = 1000 := by decide +kernel\n"
                      f"private theorem {name}_checked : checkEdges {name} = true := by decide +kernel\n")
    cycle = ("/-- Fixed-point phase coordinates for indices zero through 15999. -/\n"
             "def cycle : List (ℤ × ℤ) :=\n  " + " ++ ".join(names) + "\n")
    blocks = ("/-- Uniform phase blocks for short indexed lookups. -/\n"
              "def blocks : List (List (ℤ × ℤ)) := [" + ", ".join(names) + "]\n")
    lengths = ", ".join(f"{name}_length" for name in names)
    checked = f"{names[-1]}_checked"
    for name in reversed(names[:-1]):
        checked = f"checkEdges_append {name}_checked ({checked}) (by decide +kernel)"
    proofs = f'''

/-- The stored cycle has the exact required number of entries. -/
theorem cycle_length : cycle.length = 16000 := by
  norm_num only [cycle, List.length_append, {lengths}]

/-- The initial rotation is exactly the unit point. -/
theorem cycle_start : cycle[0]?.getD (0, 0) = ((scale : ℤ), 0) := by decide +kernel

/-- All coordinate bounds and adjacent recurrence residuals are checked
by the Lean kernel. -/
theorem cycle_checked : checkEdges cycle = true :=
  {checked}

/-- The block representation is exactly the checked flat cycle. -/
theorem blocks_flatten : blocks.flatten = cycle := by
  simp only [blocks, cycle, List.flatten_cons, List.flatten_nil, List.append_nil, List.append_assoc]

/-- Every stored block has the same exact length. -/
theorem blocks_uniform : ∀ b ∈ blocks, b.length = 1000 := by
  simp only [blocks, List.mem_cons, List.not_mem_nil, or_false]
  intro b hb
  rcases hb with {" | ".join("rfl" for _ in names)}
  {chr(10).join("· exact " + name + "_length" for name in names).replace(chr(10), chr(10) + "  ")}

/-- A periodic lookup with at most two short list traversals. -/
def lookup (n : ℕ) : ℤ × ℤ :=
  ((blocks[(n % 16000) / 1000]?.getD [])[(n % 16000) % 1000]?).getD (0, 0)

/-- Fast lookup retains the exact same checked phase coordinates. -/
theorem lookup_eq (n : ℕ) : lookup n = cycle[n % 16000]?.getD (0, 0) := by
  rw [← blocks_flatten, UniformBlockIndex.getElem?_flatten blocks
    (by decide : 0 < 1000) blocks_uniform]
  rfl

/-- A uniform enclosure for every phase in the infinite natural grid. -/
theorem cycle_error (n : ℕ) :
    |((cycle[n % 16000]?.getD (0, 0)).1 : ℝ) / scale -
        Real.cos ((n : ℝ) * (Real.pi / 8000))| ≤ 1 / 10000000000000 ∧
      |((cycle[n % 16000]?.getD (0, 0)).2 : ℝ) / scale -
        Real.sin ((n : ℝ) * (Real.pi / 8000))| ≤ 1 / 10000000000000 :=
  periodic_table_error cycle cycle_start cycle_checked (by rw [cycle_length]) n

/-- The fast periodic lookup has the same infinite-grid error guarantee. -/
theorem lookup_error (n : ℕ) :
    |((lookup n).1 : ℝ) / scale - Real.cos ((n : ℝ) * (Real.pi / 8000))| ≤
      1 / 10000000000000 ∧
    |((lookup n).2 : ℝ) / scale - Real.sin ((n : ℝ) * (Real.pi / 8000))| ≤
      1 / 10000000000000 := by
  rw [lookup_eq]
  exact cycle_error n

end RiemannGaussian.MontgomeryTaylorPhaseGrid.CertificateData
'''
    target.write_text(preamble + "\n".join(chunks) + "\n" + cycle + "\n" + blocks + proofs)
    print(f"Wrote {target.relative_to(target.parents[2])} ({len(points)} phase witnesses)")


if __name__ == "__main__":
    main()
