#!/usr/bin/env python3
"""Propose integer representations of previously checked numerical data.

Copyright (c) 2026 David Sanftenberg. Released under Apache 2.0.
The generated Lean proofs check structural and exact field agreement.
No numerical enclosure or mathematical conclusion is trusted to Python.
"""
import argparse
from fractions import Fraction as F
from pathlib import Path

from generate_montgomery_taylor_anchor_data import integer

HEADER = """ /-
Copyright (c) 2026 David Sanftenberg. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Sanftenberg
-/
""".lstrip()
ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "RiemannGaussian/CertificateData"
D, S, UNIT = 30000000, 2**40, 60000


def generate_ranges(path):
    values = {}
    for row in path.read_text().splitlines():
        i, v, d = map(int, row.split())
        if i in values:
            raise ValueError("Repeated range cell")
        values[i] = v, d
    if set(values) != set(range(166, 9472)):
        raise ValueError("Expected exactly 9306 consecutive range cells")

    def bound(l, r):
        return "(" + integer(min(values[i][0] for i in range(l, r))) + ", " + integer(
            min(values[i][1] for i in range(l, r))) + ")"

    def literal(l, r):
        b = bound(l, r)
        if l + 1 == r:
            return f"(.leaf {b})"
        m = (l + r) // 2
        return f"(.node {b} ({integer(m*UNIT)})\n{literal(l,m)}\n{literal(m,r)})"

    def join(parts):
        if len(parts) == 1:
            return parts[0]
        m = len(parts) // 2
        lt, l, cut = join(parts[:m])
        rt, _, r = join(parts[m:])
        return f"(.node {bound(l,r)} ({integer(cut*UNIT)})\n{lt}\n{rt})", l, r

    definitions, segments = [], []
    for n, i in enumerate(range(166, 9472, 128)):
        name, end = f"chunk{n:02d}", min(i + 128, 9472)
        definitions.append(f"private def {name} : Table :=\n{literal(i, end)}\n\n")
        segments.append((name, i, end))
    groups = [join(segments[g*len(segments)//8:(g+1)*len(segments)//8]) for g in range(8)]
    tree, _, _ = join(groups)
    text = HEADER + """import RiemannGaussian.CertificateData.MontgomeryTaylorRangeCells
import RiemannGaussian.MontgomeryTaylorIntegerBoxCertificate

/-!
# Integer coordinates for the complete proved continuous range table

Generated by scripts/generate_montgomery_taylor_integer_data.py.
Exact comparison with the already checked rational tree transports every
bound and every cut. The full box cover is a separate proof obligation.
-/

namespace RiemannGaussian.MontgomeryTaylorIntegerBoxCertificate.CertificateData
open MontgomeryTaylorIntegerCoordinates MontgomeryTaylorRangeTable

set_option maxRecDepth 100000
set_option maxHeartbeats 0

""" + "".join(definitions) + """
/-- The complete table with integer endpoints. -/
def table : Table :=
""" + tree + """

/-- Every cached bound and every scaled cut agrees with the rational table. -/
theorem table_agrees : CertifiedIntegerRangeTree.agrees denominator table
    MontgomeryTaylorRangeTable.CertificateData.table = true := by decide +kernel

/-- The integer table retains all continuous value and curvature bounds. -/
theorem table_valid : TableValid table 9960000 568320000 := by
  apply CertifiedIntegerRangeTree.agrees_sound denominator realBounds
    (fun x => (MontgomeryTaylorNumericalKernel.kernel x ^ 2,
      MontgomeryTaylorNumericalKernel.squaredDD x)) table
    MontgomeryTaylorRangeTable.CertificateData.table table_agrees
  convert MontgomeryTaylorRangeTable.CertificateData.table_valid using 1
  norm_num [denominator, MontgomeryTaylorRangeTable.Valid]

end RiemannGaussian.MontgomeryTaylorIntegerBoxCertificate.CertificateData
"""
    (TARGET / "MontgomeryTaylorIntegerRanges.lean").write_text(text)


def generate_anchors(point_path, sample_path):
    points = [list(map(int, r.split())) for r in point_path.read_text().splitlines()]
    samples = [list(map(int, r.split())) for r in sample_path.read_text().splitlines()]
    if len(points) != 944 or any(len(p) != 6 for p in points):
        raise ValueError("Expected 944 six-coordinate points")
    if any(len(r) != 6 for r in samples) or [(r[0], r[1]) for r in samples] != [
            (i, t) for i in range(944) for t in range(19)]:
        raise ValueError("Incomplete point samples")
    terms = [(i, s, c) for s, row in enumerate([
        [21884,33405,44711,44711,33405,21884], [74396,25604,0,25604,74396],
        [32469,67531,67531,32469], [100000,0,100000], [100000,100000], [200000]], 1)
        for i, c in enumerate(row) if c]
    p = [208856,325508,465636,465636,325508,208856]
    vector = lambda xs: "![" + ", ".join(map(integer, xs)) + "]"
    text = HEADER + """import RiemannGaussian.CertificateData.MontgomeryTaylorAnchors
import RiemannGaussian.MontgomeryTaylorIntegerBoxCertificate

/-!
# Exact integer anchor catalogue

Generated by scripts/generate_montgomery_taylor_integer_data.py.
Every field is checked against the already proved rational anchor catalogue.
No trigonometric enclosure is recomputed here.
-/

namespace RiemannGaussian.MontgomeryTaylorIntegerBoxCertificate.CertificateData

set_option maxRecDepth 100000
set_option maxHeartbeats 0

"""
    blocks = []
    for start in range(0, 944, 32):
        anchors = []
        for i in range(start, min(start+32, 944)):
            m = [3*x for x in points[i]]
            v = sum(F(p[j]*m[j], 10**9*D) for j in range(6))
            lo = [F(x, 10**9) for x in p]
            hi = lo.copy()
            for (j, s, c), (_, _, _, value, dl, du) in zip(terms, samples[i*19:(i+1)*19]):
                v += F(c*value, 100000*S)
                for k in range(j, j+s):
                    lo[k] += F(c*dl, 100000*S)
                    hi[k] += F(c*du, 100000*S)
            vi = int(v*S//1)
            li = [int(x*S//1) for x in lo]
            ui = [-int(-x*S//1) for x in hi]
            anchors.append(f"{{ sourceIndex := {i}, point := {vector(m)}, value := {integer(vi)},\n"
                           f"  lower := {vector(li)}, upper := {vector(ui)} }}")
        name = f"block{start//32:02d}"
        blocks.append(name)
        text += f"private def {name} : List Anchor := [\n" + ",\n".join(anchors) + "]\n\n"
        text += f"""private theorem {name}_valid : ∀ a ∈ {name},
    MontgomeryTaylorAnchorBounds.Valid a.decode := by
  have hc : {name}.all (checkCache MontgomeryTaylorAnchorBounds.CertificateData.lookup) =
      true := by decide +kernel
  intro a ha
  exact checkCache_sound MontgomeryTaylorAnchorBounds.CertificateData.lookup
    MontgomeryTaylorAnchorBounds.CertificateData.lookup_valid (List.all_eq_true.mp hc a ha)

"""
    text += "/-- Short consecutive blocks of verified integer anchors. -/\ndef blocks : List (List Anchor) := [" + ", ".join(blocks) + "]\n\n"
    text += """/-- Every stored cache retains its independent real analytic proof. -/
theorem blocks_valid : ∀ block ∈ blocks, ∀ a ∈ block,
    MontgomeryTaylorAnchorBounds.Valid a.decode := by
  intro block hb
  simp only [blocks, List.mem_cons, List.not_mem_nil, or_false] at hb
  rcases hb with """ + " | ".join("rfl" for _ in blocks) + "\n"
    text += "".join(f"  · exact {b}_valid\n" for b in blocks)
    text += """
/-- Fast indexed access to the complete integer catalogue. -/
def lookup (i : ℕ) : Option Anchor := catalogueLookup blocks i

/-- Every successful integer lookup carries the original real bounds. -/
theorem lookup_valid (i : ℕ) (a : Anchor) (h : lookup i = some a) :
    MontgomeryTaylorAnchorBounds.Valid a.decode :=
  catalogueLookup_valid blocks blocks_valid h

end RiemannGaussian.MontgomeryTaylorIntegerBoxCertificate.CertificateData
"""
    (TARGET / "MontgomeryTaylorIntegerAnchors.lean").write_text(text)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("ranges", type=Path)
    p.add_argument("points", type=Path)
    p.add_argument("samples", type=Path)
    args = p.parse_args()
    generate_ranges(args.ranges)
    generate_anchors(args.points, args.samples)
    print("Proposed integer tables: 9306 cells and 944 anchors; Lean agreement proofs required.")


if __name__ == "__main__":
    main()
