#!/usr/bin/env python3
"""Public-input complex corrections and exponentially spaced order aliases.

This optional experiment has bounded work per attempted cover, not a
guaranteed hit. Fixed phases are calibrated probes. Exponential-orbit
points are generated by repeated small/public powers, never by consulting
a factor, order table, or discrete-log oracle. All setup is charged.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
import runpy
import time

import gmpy2

ROOT = Path(__file__).resolve().parents[1]
LONG = runpy.run_path(str(ROOT / "scripts/probe_semiprime_long_period.py"))
QUADRATIC = LONG["QUADRATIC"]
SINGLE = LONG["SINGLE"]


class CountingRing(QUADRATIC["QuadraticRing"]):
    def __init__(self, n, discriminant):
        super().__init__(n, discriminant)
        self.multiplications = 0

    def mul(self, left, right):
        self.multiplications += 1
        return super().mul(left, right)


def prepare(n, discriminant=-1):
    """The existing public separator and full smooth projection, charged once."""
    if n < 4:
        raise ValueError("composite n >= 4 required")
    if n % 2 == 0:
        return None, None, {"status": "factor", "factor": 2, "stage": "even"}
    root = math.isqrt(n)
    if root*root == n:
        return None, None, {"status": "factor", "factor": root, "stage": "square"}
    g = math.gcd(discriminant, n)
    if g != 1:
        return None, None, {"status": "factor" if g < n else "nonunit-colour",
                            "factor": g if g < n else None, "stage": "colour"}
    colour = int(gmpy2.jacobi(discriminant, n))
    ring = CountingRing(n, discriminant)
    bound = SINGLE["ceil_root"](n, 6)
    for parameter in range(1, 33):
        den = (parameter*parameter-discriminant) % n
        g = math.gcd(den, n)
        if 1 < g < n:
            return None, None, {"status": "factor", "factor": g, "stage": "parameter"}
        if g != 1:
            continue
        inv = pow(den, -1, n)
        unit = ((parameter*parameter+discriminant)*inv % n, 2*parameter*inv % n)
        alpha = ring.power(unit, n-colour)
        if alpha != (1, 0):
            break
    else:
        return None, None, {"status": "kernel-unresolved", "factor": None}
    powers = SINGLE["projection_powers"](bound, root+1)
    info = {"bound": bound, "discriminant": discriminant, "jacobi": colour,
            "base_parameter": parameter, "projection_count": len(powers)}
    for _, exponent in [(0, 1)] + powers:
        alpha = ring.power(alpha, exponent)
        g = math.gcd(alpha[0]-1, n)
        if g != 1:
            return None, None, {**info,
                "status": "factor" if g < n else "shared-projection",
                "factor": g if g < n else None, "stage": "projection",
                "quadratic_multiplications": ring.multiplications}
    return ring, alpha, info


def inspect_batch(n, batch, node, roots, points):
    """A shared collision must not prevent inspection of later targets."""
    shared = 0
    for j, value in enumerate(batch.evaluate(node[0], points)):
        g = math.gcd(value, n)
        if g == n:
            g = LONG["WEIGHTED"]["descend"](node, points[j], n)
            if not g or g == n:
                shared += 1
                continue
        if g and 1 < g < n:
            i = next(i for i, root in enumerate(roots) if (points[j]-root) % g == 0)
            return {"status": "factor", "factor": g, "baby_index": i,
                    "giant_index": j, "root": roots[i], "point": points[j],
                    "shared_targets": shared}
    return {"status": "no-collision", "factor": None, "shared_targets": shared}


def factor_phases(n, phases=(0, -13, 15), degree=6, discriminant=-1):
    """Rotate before projecting. Each extra phase costs an additional batch.

    If phase = alpha**c, the inverse channel is e+f+2c == 0 (mod order).
    The equal channel is unchanged. No phase is inferred from a private order.
    """
    if degree < 1 or not phases:
        raise ValueError("positive degree and a nonempty phase budget required")
    ring, alpha, info = prepare(n, discriminant)
    if ring is None:
        return info
    bound = info["bound"]
    f = lambda x: LONG["dickson_integer"](x, degree)
    baby = LONG["quadratic_polynomial_powers"](ring, alpha, f, degree, bound)
    giant = LONG["quadratic_polynomial_powers"](
        ring, alpha, lambda j: f(bound*j), degree, bound, start=1)
    total_stats = dict.fromkeys(("convolutions", "packed_coefficients", "monic_reductions"), 0)
    history = []
    for c in phases:
        phase = ring.power(alpha if c >= 0 else ring.inverse_one(alpha), abs(c))
        roots = [2*ring.mul(phase, value)[0] % n for value in baby]
        points = [2*ring.mul(phase, value)[0] % n for value in giant]
        batch = LONG["MonicBatch"](n)
        result = inspect_batch(n, batch, batch.tree(roots), roots, points)
        for key, value in batch.stats().items():
            total_stats[key] += value
        history.append({"phase_exponent": c, "status": result["status"],
                        "shared_targets": result["shared_targets"]})
        if result["factor"]:
            i, j = result["baby_index"], result["giant_index"]+1
            g = result["factor"]
            channels = []
            left, right = baby[i], giant[j-1]
            if all((x-y) % g == 0 for x, y in zip(left, right)):
                channels.append("equal")
            rotated_product = ring.mul(ring.mul(phase, phase), ring.mul(left, right))
            if (rotated_product[0]-1) % g == 0 and rotated_product[1] % g == 0:
                channels.append("rotated-inverse")
            assert channels
            return {**info, **result, **total_stats, "stage": "phase-cover",
                    "phase_exponent": c, "verified_channels": channels,
                    "collision_exponents": [str(f(i)), str(f(bound*j))],
                    "phases_used": len(history), "history": history,
                    "quadratic_multiplications": ring.multiplications}
    return {**info, **total_stats, "status": "phase-budget-exhausted", "factor": None,
            "history": history, "quadratic_multiplications": ring.multiplications}


def factor_orbits(n, bases=(2, 3), discriminant=-1):
    """One product tree, two exponential exponent orbits, doubling targets.

    Baby exponents are a**i and target exponents b**j. Group elements are
    generated by raising the previous element to a or b. Positive indices
    avoid the vacuous a**0=b**0=1 identity. Constant bases cost O(B) ring
    operations; bases N,N+1 cost O(B log N). Either is a bounded attempt.
    """
    if min(bases) < 2 or bases[0] == bases[1]:
        raise ValueError("distinct bases >= 2 required")
    ring, alpha, info = prepare(n, discriminant)
    if ring is None:
        return info
    bound = info["bound"]
    value = alpha
    baby = []
    for _ in range(bound):
        value = ring.power(value, bases[0])
        baby.append(value)
    roots = [2*value[0] % n for value in baby]
    batch = LONG["MonicBatch"](n)
    node = batch.tree(roots)
    value, visited, size, batches = alpha, 0, 1, 0
    shared = 0
    while visited < bound:
        count = min(size, bound-visited)
        target = []
        for _ in range(count):
            value = ring.power(value, bases[1])
            target.append(value)
        result = inspect_batch(n, batch, node, roots, [2*v[0] % n for v in target])
        batches += 1
        shared += result["shared_targets"]
        if result["factor"]:
            i, j = result["baby_index"]+1, visited+result["giant_index"]+1
            g = result["factor"]
            left, right = baby[i-1], target[result["giant_index"]]
            equal = all((x-y) % g == 0 for x, y in zip(left, right))
            inverse = all((x-y) % g == 0 for x, y in zip(left, ring.inverse_one(right)))
            assert equal or inverse
            return {**info, **result, **batch.stats(), "stage": "exponential-orbits",
                    "bases_decimal": [str(b) for b in bases], "baby_exponent_index": i,
                    "giant_exponent_index": j, "giant_count": visited+count,
                    "target_batches": batches, "verified_channel": "equal" if equal else "inverse",
                    "quadratic_multiplications": ring.multiplications}
        visited += count
        size *= 2
    return {**info, **batch.stats(), "status": "orbit-budget-exhausted", "factor": None,
            "bases_decimal": [str(b) for b in bases], "target_batches": batches,
            "shared_targets": shared, "quadratic_multiplications": ring.multiplications}


def validate():
    count = 0
    for p in (3, 5, 7, 11, 13, 17, 19):
        for d in (-1, 2):
            ring = CountingRing(p, d)
            units = [(x, y) for x in range(p) for y in range(p) if ring.norm((x, y)) == 1]
            for phase in units:
                for left in units:
                    for right in units:
                        signal = ring.mul(phase, left)[0] == ring.mul(phase, right)[0]
                        product = ring.mul(ring.mul(phase, phase), ring.mul(left, right))
                        assert signal == (left == right or product == (1, 0))
                        count += 1
    # Shared targets precede a separating one: inspect all targets.
    batch = LONG["MonicBatch"](35)
    roots = [1]
    witness = inspect_batch(35, batch, batch.tree(roots), roots, [1, 6])
    assert witness["factor"] == 5 and witness["shared_targets"] == 1
    return {"rotated_local_trace_checks": count, "shared_target_continuation_checks": 1}


def perfect_alignment(n):
    """A public phase can force both hidden legs to collide, giving only N."""
    ring, alpha, info = prepare(n)
    if ring is None:
        return {"status": "early-stage", "result": info}
    e = LONG["dickson_integer"](1, 6)
    f = LONG["dickson_integer"](info["bound"], 6)
    assert (e+f) % 2 == 0
    c = -(e+f)//2
    phase = ring.power(alpha if c >= 0 else ring.inverse_one(alpha), abs(c))
    left = ring.mul(phase, ring.power(alpha if e >= 0 else ring.inverse_one(alpha), abs(e)))
    right = ring.mul(phase, ring.power(alpha if f >= 0 else ring.inverse_one(alpha), abs(f)))
    assert left[0] == right[0]
    assert ring.mul(left, right) == (1, 0)
    g = math.gcd(left[0]-right[0], n)
    assert g == n
    return {"phase_exponent_decimal": str(c), "gcd_decimal": str(g),
            "quadratic_multiplications": ring.multiplications,
            "interpretation": "Exact globally perfect alignment is nonseparating."}


def report():
    rows = []
    # Factors below are validation references only; algorithms receive N.
    controls = ((6827, 7187), (2346272483, 3649327547), (661911275027, 720957498683))
    benchmark = json.loads((ROOT / "docs/semiprime-long-period-benchmark.json").read_text())
    challenges = [(int(s["N_decimal"]), tuple(int(x) for x in s["reference_factors_decimal"]))
                  for row in benchmark["rows"] for s in row["samples"]
                  if s["results"]["dickson6"]["factor"] is None]
    for n, factors in [(p*q, (p, q)) for p, q in controls]+challenges:
        tests = {}
        names = [("phases_0_minus13_plus15", lambda: factor_phases(n)),
                 ("orbits_2_3", lambda: factor_orbits(n, (2, 3))),
                 ("orbits_2_5", lambda: factor_orbits(n, (2, 5)))]
        # Adjacent public exponents have a larger charged constant. Only the
        # small/64-bit controls are tested, not an asserted universal bound.
        if n.bit_length() <= 64:
            names.append(("orbits_N_Nplus1", lambda: factor_orbits(n, (n, n+1))))
        for name, function in names:
            start = time.perf_counter()
            result = function()
            assert result["factor"] in (None, *factors)
            tests[name] = {"result": result, "ms": 1000*(time.perf_counter()-start)}
        rows.append({"N_decimal": str(n), "reference_factors_decimal": [str(p) for p in factors],
                     "tests": tests, "perfect_public_alignment": perfect_alignment(n)})
    paths = [Path(__file__), ROOT / "scripts/probe_semiprime_long_period.py",
             ROOT / "RiemannGaussian/SemiprimeLongPeriodExtraction.lean"]
    return {"controls_and_existing_challenges": rows, "checks": validate(),
            "scope": "Selected regression/challenge inputs, not a fresh success-rate benchmark. "
                     "Phases -13 and +15 were calibrated on a prior control. "
                     "No algorithm consults reference factors or local orders. "
                     "Timings are single full-call observations, not runtime certificates.",
            "source_hashes": {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest()
                              for p in paths}}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("validate", "probe", "factor"))
    parser.add_argument("n", nargs="?", type=int)
    parser.add_argument("--algorithm", choices=("phase", "orbit"), default="phase")
    parser.add_argument("--phase", nargs="+", type=int, default=[0, -13, 15])
    parser.add_argument("--bases", nargs=2, type=int, default=[2, 3])
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    if args.mode == "probe":
        result = report()
    elif args.mode == "validate":
        result = validate()
    elif args.n is None:
        parser.error("factor requires N")
    elif args.algorithm == "phase":
        result = factor_phases(args.n, args.phase)
    else:
        result = factor_orbits(args.n, args.bases)
    encoded = json.dumps(LONG["safe_json"](result), indent=2)+"\n"
    if args.output:
        args.output.write_text(encoded)
    print(encoded, end="")


if __name__ == "__main__":
    main()
